unit uTR4WStrings;

{
  THE APPLICATION'S USER-FACING TEXT, AS resourcestring.

  GENERATED by tools/i18n/pas2res.py from src/lang/tr4w_consts_eng.pas.
  Do not hand-edit: regenerate. To change the ENGLISH, change it in the .po
  catalogue and run po2pas.py, or change the table and regenerate -- either
  way the change flows from one place.

  WHY resourcestring AND NOT const. The compiler puts these in a resource
  string table and emits uTR4WStrings.rsj beside the object file, so rstconv can
  extract them and LazUtils' Translations unit can REPLACE them at run time
  from a .po. One binary, every language. A const is inlined into code and is
  invisible to all of that.

  THE IDENTIFIER IS THE TRANSLATION KEY. It appears in the catalogues twice --
  as msgctxt and as the `#: utr4wstrings:<name>` reference the run-time loader
  matches on. RENAMING ONE ORPHANS ITS TRANSLATION IN EVERY LANGUAGE, silently.
  That is why these kept their TC_/RC_ spelling when they moved here, against
  the S<Area><Thing> convention uAppStrings uses for strings written new.

  RC_ constants that appear ONLY in res/Tr4w.rc are deliberately absent: their
  text reaches the screen from the compiled .RES, so a resourcestring here
  would translate nothing. They retire as their dialogs become LCL forms.
}

interface

resourcestring

   { TC_ -- messages, prompts and labels }


   // General
   TC_TRANSLATION_LANGUAGE               = 'ENGLISH';
   TC_TRANSLATION_AUTHOR                 = 'N4AF';
   TC_TRANSLATOR_EMAIL                   = 'ny4i@ny4i.com';
   TC_TRANSLATION_CREDIT                 = '%s translation by %s';
   TC_WAGWarn                            = 'Warning: Out of WAG allowed frequency range';
   TC_FREQ                               = 'Freq';
   TC_POINTS                             = 'Pts';
   TC_OP                                 = 'Op';
   TC_INVALID                            = 'Invalid Entry';
   TC_FREQ_ZERO                          = 'ERROR: Invalid Frequency logged';
   TC_FREQ_OFF                           = 'SHOW FREQUENCY IN LOG is turned off';
   TC_CHECKCALLSIGN                      = 'Check callsign';
   TC_2RADIO_WARN                        = 'ERROR: 2 Radios on single band';
   TC_FREQUENCYFORCALLINKHZ              = 'frequency for %s in kHz';
   TC_DIFVERSION                         = '%s is from a different program version.'#13'TR4W is expecting version %s.'#13'The file you are trying to read version %s.';
   TC_M                                  = 'm';   //minute
   TC_S                                  = 's';   //second
   TC_RADIO1                             = 'Radio 1';
   TC_RADIO2                             = 'Radio 2';
   TC_DISBALE_CIV                        = 'Disable "CI-V Transceive" mode in your ICOM rig. Refer to instruction manual of your radio.';
   TC_SERIAL_FORMAT_LABEL                = 'DATA/PARITY/STOP';
   TC_HAMLIB_ID_LABEL                    = 'HAMLIB ID';
   TC_PORT_CONFLICT_STARTUP              = 'RADIO ONE and RADIO TWO are both configured to use %s. RADIO ONE keeps the port; RADIO TWO CAT control is disabled until one radio''s CONTROL PORT is changed.';
   TC_PORT_CONFLICT_DIALOG               = '%s is already configured as %s. Two devices cannot share a serial port.';
   TC_PORT_CONFLICT_PROCEED              = 'Apply anyway?';

   // MAIN
   TC_YOU_ARE_USING_THE_LATEST_VERSION   = 'You are using the latest version';
   TC_SET_VALUE_OF_SET_NOW               = 'Set value of %s. Set now?';
   TC_CONFIGURATION_FILE                 = 'Configuration file';
   TC_CURRENT_OPERATOR_CALLSIGN          = 'current operator callsign';
   TC_APPENDIMPORTEDQSOSTOCURRENTLOG     = 'Append imported QSOs to current log?';
   TC_QSO_IMPORTED                       = 'Qs imported.';   //- '345 Qs imported.'
   TC_ISADUPE                            = '%s is a dupe!!';
   TC_ERRORINLOGFILE                     = 'Error in log file!';
   TC_HASIMPROPERSYNTAX                  = '%s has improper syntax!!';
   TC_PREF_OR_CQZONE                     = 'Enter your CQ ZONE or JA PREFECTURE';
   TC_SORRYNOLOG                         = 'Sorry!! NO LOG = TRUE which prohibits logging QSOs on this computer';
   TC_SETCOMPUTERIDVALUE                 = 'Set COMPUTER ID value.';
   TC_WANTTOCONVERTLOG                   = 'Would you like to convert this log to the latest format?';
   TC_LOGFILENOTFOUND                    = 'Log file not found';
   TC_CANNOTBACKUPLOG                    = 'Could not make a backup copy of ';
   TC_CANNOTCOPYLOGREADONLY              = 'Cannot copy log file -- target exists and is read-only';
   TC_BACKUPCREATED                      = 'Log file backup created';
   TC_CANNOTRENAME                       = 'Can not rename';
   TC_CLEARALLLOGS                       = '"CLEARALLLOGS" to clear all logs in network';
   TC_CLEAR_DUPESHEET_NET                = '"CLEARDUPESHEET" to clear all dupesheets in network';
   TC_CLEAR_MULTSHEET_NET                = '"CLEARMULTSHEET" to clear all multsheets in network';
   TC_REALLYWANTTOCLEARTHELOG            = 'Do you really want to clear the current log?';
   TC_MESSAGETOSENDVIANETWORK            = 'message to send via network';
   TC_SENDTIMETOCOMPUTERSONTHENETWORK    = 'Do you really want to send time to computers on the network?';
   TC_RULESONSM3CER                      = 'Rules for %s contest at WA7BNM Contest Calendar';
   TC_RULESONQRZRU                       = 'Rules for %s contest at QRZ.RU';
   TC_NOTE                               = 'note';
   TC_DUPESHEETCLEARED                   = 'Dupe sheet cleared!';
   TC_MULTSHEETCLEARED                   = 'Mult sheet cleared!';
   TC_YESTOCLEARTHEDUPESHEET             = '"YES" to clear the dupesheet';
   TC_CLEARMULTTOCLEARMULTSHEET          = '"CLEARMULT" to clear the multsheet';
   TC_TRANSMITFREQUENCYKILOHERTZ         = 'transmit frequency (kiloHertz): ';
   TC_SPRINTQSYRULE                      = 'SPRINT QSY RULE!!!';
   TC_PADDLE                             = 'Paddle';
   TC_FOOTSW                             = 'Footsw.';
   TC_SUN                                = 'Sun';
   TC_MON                                = 'Mon';
   TC_TUE                                = 'Tue';
   TC_WED                                = 'Wed';
   TC_THU                                = 'Thu';
   TC_FRI                                = 'Fri';
   TC_SAT                                = 'Sat';

   // uMP3Recorder
   TC_LAME_ERROR                         = 'You may download it from';
   TC_THISVERSION                        = 'You have ';
   TC_WASBUILDIN                         = ' installed (build date ';
   TC_DOYOUWANTTOCHECKTHELATESTVERSION   = 'Would you like to check for a possible newer version of  TR4W ?';

   // NEW CONTEST
   TC_LABRE                              = 'Enter 2 char QTH ID';
   TC_EUDX                               = 'EU country, enter your four character country code';
   TC_IRTS                               = 'EI/GI, enter your County';
   TC_LATEST_CONFIG_FILE                 = 'Latest config file';
   TC_OPENCONFIGURATIONFILE              = ' - Open configuration file or start a new contest';
   TC_FOLDERALREADYEXISTSOVERWRITE       = 'Folder "%s" already exists.'#13'Overwrite ?';
   TC_IAMIN                              = '&I am in %s';
   TC_CROAT                              = 'I am in Croatia';
   TC_NEWENGLANDSTATEABREVIATION         = 'Enter your New England state abbreviation'#13'(ME, NH, VT, MA, CT, RI):';
   TC_ENTERTHEQTHTHATYOUWANTTOSEND       = 'Enter the QTH that you want to send:';
   TC_ENTERSTATEFORUSPROVINCEFORCANADA   = 'Enter state for U.S., province for Canada:';
   TC_ENTERYOUROBLASTID                  = 'Enter your oblast ID:';
   TC_ENTERYOURPROVINCEID                = 'Enter your province ID:';
   TC_ENTERYOURCOUNTYCODE                = 'Enter your county code:';
   TC_ENTERYOURDOK                       = 'Enter your DOK:';
   TC_ENTERYOURDISTRICTABBREVIATION      = 'Enter your district abbreviation:';
   TC_ENTERYOURFOCNUMBER                 = 'Enter your FOC number:';
   TC_ENTERYOURRDAID                     = 'Enter your RDA ID:';
   TC_ENTERYOURIOTAREFERENCEDESIGNATOR   = 'Enter your IOTA Reference Designator (WITH DASH and no leading zeros delimiting # e.g. EU-5)';
   TC_ENTERYOURPARKREFERENCEDESIGNATOR   = 'Enter your POTA Park Reference Designator (WITH DASH e.g. K-1234)';
   TC_ENTERYOURCITYIDENTIFIER            = 'Enter your city identifier:';
   TC_ENTERYOURNAME                      = 'Enter your name:';
   TC_ENTERTHELASTTWODIGITSOFTHEYEAR     = 'Enter the last two digits of the year of your first official amateur radio license:';
   TC_ENTERYOURZONE                      = 'Enter your zone:';
   TC_ENTERYOURGEOGRAPHICALCOORDINATES   = 'Enter your geographical coordinates'#13'(e.g. 55N37O for Moscow):';
   TC_ENTERSUMOFYOURAGEANDAMOUNT         = 'Enter sum of your age and amount of years elapsed since your first QSO (e.g. 28+14=42):';
   TC_OZCR                               = 'Enter three-letters number:';
   TC_ENTERYOURSTATECODE                 = 'Enter your state code:';
   TC_ENTERYOURFOURDIGITGRIDSQUARE       = 'Enter your four digit grid square:';
   TC_RFAS                               = 'Enter your geographical coordinates:';
   TC_ENTERYOURSIXDIGITGRIDSQUARE        = 'Enter your six digit grid square:';
   TC_ENTERYOURNAMEANDSTATE              = 'Enter your name (and state if you are in North America):';
   TC_ENTERYOURNAMEANDQTH                = 'Enter your name and QTH (US state, Canadian Province or DX country) or member number:';
   TC_ENTERYOURPRECEDENCECHECKSECTION    = 'Enter your precedence, your check'#13'(last two digits of year licensed) and ARRL section:';
   TC_ENTERYOURQTHANDTHENAME             = 'Enter your QTH that you want to send'#13'and the name you want to use:';
   TC_ENTERFIRSTTWODIGITSOFYOURQTH       = 'Enter first two digits of your QTH:';
   TC_ENTERYOURAGEINMYSTATEFIELD         = 'Enter your age in MY STATE field:';
   TC_ENTERYOURQTHORPOWER                = 'Enter your QTH that you want to send if you are in North America or your power as MY STATE if outside:';
   TC_ENTERFIRSTTWOLETTERSOFYOURGRID     = 'Enter first two letters of your grid square:';
   TC_ENTERYOURSQUAREID                  = 'Enter your square ID:';
   TC_ENTERYOURMEMBERSHIPNUMBER          = 'Enter your membership number:';
   TC_ENTERYOURCONTINENT                 = 'Enter your continent (and possible additional ID, i.e. SA or NAQ)';
   TC_ENTERYOURCOUNTYORSTATEPOROVINCEDX  = 'Enter your county if you are in %s state. Enter your state, Canadian Province or "DX" if outside of %s:';
   TC_ENTERYOURISTRICTIFINVE7            = 'Enter your federal district if in British Columbia, or your State/Province';   //4.97.6
   TC_PREFECTURE                         = 'Enter your prefecture:';
   TC_STATIONCLASS                       = 'Enter your station class:';
   TC_AGECALLSIGNAGE                     = 'Enter your age (and Silent Key callsign and age):';
   TC_DEPARTMENT                         = 'Enter your department:';
   TC_ENTERYOURRDAIDORGRID               = 'Enter your RDA ID (for UA1A stations) or four digit grid square:';
   TC_ENTERYOURBRANCHNUMBER              = 'Enter your Branch number:';
   TC_ENTERYOURPOSTCODE                  = 'Enter your postcode:';
   TC_ENTERYOURDISTRICTCODE              = 'If in UK/EI, enter your 2 digit district code';
   TC_ISLANDSTATION                      = 'Island station';
   TC_NEWENGLAND                         = 'New England';
   TC_CALIFORNIA                         = 'California';
   TC_FLORIDA                            = 'Florida';
   TC_MICHIGAN                           = 'Michigan';
   TC_MINNESOTA                          = 'Minnesota';
   TC_OHIO                               = 'Ohio';
   TC_WASHINGTON                         = 'Washington';
   TC_WISCONSIN                          = 'Wisconsin';
   TC_TEXAS                              = 'Texas';
   TC_NORTHAMERICA                       = 'North America';
   TC_RUSSIA                             = 'Russia';
   TC_UKRAINE                            = 'Ukraine';
   TC_CZECHREPUBLICORINSLOVAKIA          = 'Czech Republic or in Slovakia';
   TC_BULGARIA                           = 'Bulgaria';
   TC_ROMANIA                            = 'Romania';
   TC_HUNGARY                            = 'Hungary';
   TC_YUGOSLAVIA                         = 'Yugoslavia';
   TC_UKEI                               = 'If in Uk/EI enter your 2 digit district code';
   TC_BELGIUM                            = 'Belgium';
   TC_NETHERLANDS                        = 'Netherlands';
   TC_STPETERSBURGOBLAST                 = 'St.Petersburg / oblast';
   TC_GERMANY                            = 'Germany';
   TC_UK                                 = 'UK';
   TC_ARKTIKACLUB                        = 'club';
   TC_POLAND                             = 'Poland';
   TC_KAZAKHSTAN                         = 'Kazakhstan';
   TC_ITALY                              = 'Italy';
   TC_SWITZERLAND                        = 'Switzerland';
   TC_HQ                                 = 'HQ (HQ station)';
   TC_CIS                                = 'CIS';
   TC_SPAIN                              = 'Spain';
   TC_JAPAN                              = 'Japan';
   TC_CANADA                             = 'Canada';
   TC_FRANCE                             = 'France';
   TC_HQ_OR_MEMBER                       = 'HQ or member';
   TC_IRELAND                            = 'Ireland';
   TC_GC                                 = 'special two character designator';
   TC_GAGARIN                            = 'special two char ID';

   // UTELNET
   TC_TELNET                             = 'Connect'#0'Disconnect'#0'Commands'#0'Freeze'#0'Clear'#0'SH/50'#0#0;
   TC_YOURNOTCONNECTEDTOTHEINTERNET      = 'YOU ARE NOT CONNECTED TO THE INTERNET!';
   TC_GETHOST                            = 'GET HOST..';
   TC_SERVER                             = 'SERVER: %s';
   TC_HOST                               = 'HOST  : %s';
   TC_CONNECT                            = 'CONNECT..';
   TC_CONNECTED                          = 'CONNECTED';
   TC_YOUARESPOTTEDBYANOTHERSTATION      = 'You are spotted by another station.';

   // UNET
   TC_CONNECTIONTOTR4WSERVERLOST         = 'Connection to TR4WSERVER %s:%d lost.';
   TC_COMPUTERCLOCKISSYNCHRONIZED        = 'Computer clock is synchronized.';
   TC_CONNECTINGTO                       = 'Connecting to ';
   TC_CONNECTTOTR4WSERVERFAILED          = 'Connect to TR4WSERVER failed. Check SERVER PASSWORD value!!';
   TC_CONNECTEDTO                        = 'Connected to ';
   TC_DISCONNECTEDFROM                   = '** DISCONNECTED from ';
   TC_AUTOSYNCHRONIZINGLOG               = 'Auto-synchronizing log from server.';
   TC_FAILEDTOCONNECTTO                  = 'Failed to connect to ';
   TC_SERVERANDLOCALLOGSAREIDENTICAL     = 'Server and local logs are identical.';
   TC_NETWORK                            = 'Network : %s %s:%d';
   TC_SERVER_LOG_CHANGED                 = 'Server log changed. %u QSO(s) updated. Do logs synchronizing (Ctrl+Alt+S).';
   TC_ALL_LOGS_NETWORK_CLEARED           = 'All logs in TR4W network cleared.';

   // UGETSCORES
   TC_FAILEDTOCONNECTTOGETSCORESORG      = 'Failed to connect';
   TC_NOANSWERFROMSERVER                 = 'No answer from server';
   TC_UPLOADEDSUCCESSFULLY               = 'Uploaded successfully.';
   TC_FAILEDTOLOAD                       = 'Failed to load. View getscoresanswer.html for details.';

   // UBANDMAP
   TC_SOURCE                             = 'Source: %s';
   TC_MIN                                = '%u min.';

   // LOGWIND
   TC_CQTOTAL                            = 'CQ total: %u';
   TC_REPEATING                          = 'Repeating %s  Listen time = %u msec - PgUp/Dn to adjust or ESCAPE';
   TC_NEWTOUR                            = 'New tour %d/%d';
   TC_ENTER                              = 'Enter %s :';
   TC_PTS                                = '%d Pts';
   TC_RATE                               = 'Rate = %u';
   TC_LAST60                             = 'Last 60 = %d';
   TC_THISHR                             = 'This hr = %d';
   TC_BAND_CHANGES                       = 'Bn. ch. = %d';
   TC_HAVEQTCS                           = 'Have %u QTCs';
   TC_INSERT                             = 'INSERT';
   TC_OVERRIDE                           = 'OVERRIDE';
   TC_UNKNOWNCOUNTRY                     = 'Unknown country';

   // UCALLSIGNS
   TC_DUPESHEET                          = 'Dupesheet - %sm-%s';

   // LOGEDIT
   TC_QSONEEDSFOR                        = ' QSO needs for %s :';
   TC_MULTNEEDSFOR                       = ' Mult needs for %s :';
   TC_MISSINGMULTSREPORT                 = 'Missing mults report: %u countries on at least %u but not all bands.';

   // LOGDUPE
   TC_THEREWERECALLS                     = 'There were %u calls found in initial exchange file.'#13'+%u dupe(s)';
   TC_RESTARTBINISFORADIFFERENTCONTEST   = 'RESTART.BIN is for a different contest.';

   // LOGSTUFF
   TC_NOTENOUGHINFOINEXCHANGE            = 'Not enough info in exchange!!';
   TC_IMPROPERDOMESITCQTH                = 'Improper domestic QTH!!';
   TC_IMPROPERDOMESITCQTHORMISSINGNAME   = 'Improper domestic QTH or missing name!!';
   TC_MISSINGQTHANDORNAME                = 'Missing QTH and/or name!!';
   TC_NOQSONUMBERFOUND                   = 'No QSO number found!!';
   TC_IMPROPERZONENUMBER                 = 'Improper zone number!!';
   TC_IMPROPERCONTINENT                  = 'Improper continent!!';
   TC_SAVINGTO                           = 'Saving %s to %s';
   TC_FILESAVEDTOFILESUCCESSFULLY        = 'File saved to file successfully.';
   TC_FILESAVEDTOSUCCESSFULLY            = 'File saved to %s successfully.';

   // LOGSEND
   TC_WAITINGFORYOUENTERSTRENGTHOFRST    = 'Waiting for you enter strength of RST (Single digit)!!';

   // COUNTRY9
   TC_C9_NORTHAMERICA                    = 'North America';
   TC_C9_SOUTHAMERICA                    = 'South America';
   TC_C9_EUROPE                          = 'Europe';
   TC_C9_AFRICA                          = 'Africa';
   TC_C9_OCEANIA                         = 'Oceania';
   TC_C9_ANTARTICA                       = 'Antartica';
   TC_C9_ASIA                            = 'Asia';
   TC_C9_UNKNOWN                         = 'Unknown';

   // USTATIONS
   TC_STATIONSINMODE                     = 'Stations in %s mode';

   // USPOTS
   TC_SPOTS                              = '%d spots';

   // uSendKeyboard
   TC_SENDINGSSBWAVFILENAME              = 'Sending SSB .wav filename. Use ENTER to play, Escape/F10 to exit.';

   // QTC
   TC_WASMESSAGENUMBERCONFIRMED          = 'Was message number %u confirmed?';
   TC_DOYOUREALLYWANTSTOPNOW             = 'Do you really want stop now?';
   TC_QTCABORTEDBYOPERATOR               = 'QTC aborted by operator.';
   TC_DOYOUREALLYWANTTOABORTTHISQTC      = 'Do you really want to abort this QTC?';
   TC_NEXT                               = '< Next';
   TC_QTC_FOR                            = '%s for %s';
   TC_QTC_CALLSIGN                       = 'Callsign :';
   TC_ENTERQTCMAXOF                      = 'Enter QTC #/# (max of %d) :';
   TC_DOYOUREALLYWANTTOSAVETHISQTC       = 'Do you really want to save this QTC?';
   TC_EDITQTCPRESSYESTOEDITQTCORNOTOLOG  = 'Edit QTC? Press Yes to edit QTC or  No to log ';
   TC_CHECKQTCNUMBER                     = 'Check QTC number';
   TC_CHECKTIME                          = 'Check time';

   // UOPTION
   TC_COMMAND                            = 'Command';
   TC_VALUE                              = 'Value';
   TC_INFO                               = 'Info';
   TC_YOUCANCHANGETHISINYOURCONFIGFILE   = 'You can only change this in your config file.';

   // UEDITQSO
   TC_CHECKDATETIME                      = 'Check Date/Time !!';
   TC_SAVECHANGES                        = 'Save changes?';

   // LOGCW
   TC_WPMCODESPEED                       = 'WPM code speed';
   TC_CQFUNCTIONKEYMEMORYSTATUS          = 'CQ FUNCTION KEY MEMORY STATUS';
   TC_EXCHANGEFUNCTIONKEYMEMORYSTATUS    = 'EXCHANGE FUNCTION KEY MEMORY STATUS';
   TC_OTHERCWMESSAGEMEMORYSTATUS         = 'Other CW message memory status';
   TC_OTHERSSBMESSAGEMEMORYSTATUS        = 'Other SSB message memory status';
   TC_PRESSCQFUNCTIONKEYTOPROGRAM        = ' Press CQ function key to program (F1, AltF1, CtrlF1), or ESCAPE to exit) : ';
   TC_PRESSEXFUNCTIONKEYTOPROGRAM        = 'Press ex function key to program (F3-F12, Alt/Ctrl F1-F12) or ESCAPE to exit:';
   TC_NUMBERORLETTEROFMESSAGETOBEPROGRAM = 'Number or letter of message to be programmed (1-9, A-C, or ESCAPE to exit):';
   TC_CWDISABLEDWITHALTK                 = 'CW disabled with Alt-K!!  Use Alt-K again to enable.';
   TC_VOICEKEYERDISABLEDWITHALTK         = 'Voice keyer disabled with Alt-K!!  Use Alt-K again to enable.';

   // LOGCFG
   TC_NOCALLSIGNSPECIFIED                = 'No callsign specified!!';
   TC_NOFLOPPYFILESAVENAMESPECIFIED      = 'No floppy file save name specified.';
   TC_UNABLETOFIND                       = 'Unable to find %s .';
   TC_INVALIDSTATEMENTIN                 = 'Invalid statement in %s !!'#13#13'Line %u'#13'%s';
   TC_UNABLETOFINDCTYDAT                 = 'Unable to find CTY.DAT country file!!'#13'Make sure this file is in the same directory as the program.';
   TC_INVALIDSTATEMENTINCONFIGFILE       = '%s:'#13'Invalid statement in config file.'#13#13'Line %u'#13'%s';
   TC_PARAMETERHASNOVALUE                = 'Parameter "%s" has no value in the config file -- left at its default.';

   // LOGSUBS1
   TC_RECORDDVPPRESSESCAPEORRETURNTOSTOP = 'Recording DVP. Press ESCAPE or RETURN to stop.';
   TC_ALTRCOMMANDDISABLED                = 'Alt-R command requires TWO RADIO MODE = TRUE';
   TC_NOCQMESPROGRAMMEDINTOCQMEMORYALTF1 = 'No CQ message programmed into CQ MEMORY AltF1.';
   TC_THIS_FILE_DOES_NOT_EXIST           = 'This file does not exist. Create an empty file for editing?';

   // LOGSUBS2
   TC_ALTDCOMMANDDISABLED                = 'Alt-D command requires TWO RADIO MODE = TRUE';
   TC_BANDCHANGEDISABLED                 = 'Band change requires MULTIPLE BANDS = TRUE once the log has QSOs';
   TC_YOUHAVERESTOREDTHELASTDELETED      = 'You have restored the last deleted log entry!!';
   TC_YOUHAVEDELETEDTHELASTLOGENTRY      = 'You have deleted the last log entry!!  Use Alt-Y to restore it.';
   TC_DOYOUREALLYWANTTOEXITTHEPROGRAM    = 'Do you really want to exit the program?';
   TC_YOUARENOWTALKINGTOYOURPACKETPORT   = 'You are now talking to your packet port.  Use Control-B to exit.';
   TC_YOUALREADYWORKEDIN                 = 'You already worked %s in %s!!';
   TC_ISADUPEANDWILLBELOGGEDWITHZERO     = '%s is a dupe and will be logged with zero QSO points.';
   TC_LOGFILESIZECHECKFAILED             = 'LOG FILE SIZE CHECK FAILED!!!!';

   // JCTRL2
   TC_NEWVALUE                           = 'new value';

   // TREE
   TC_ALREADYEXISTSOKAYTODELETE          = '%s already exists.'#13#13'Okay to delete?';

   // UWINKEY
   TC_WINKEYERENABLE                     = '&Winkeyer enable';
   TC_AUTOSPACE                          = '&Autospace';
   TC_CTSPACING                          = 'C&T spacing';
   TC_SIDETONE                           = '&Sidetone';
   TC_PADDLESWAP                         = 'Paddle swa&p';
   TC_IGNORESPEEDPOT                     = '&Ignore speed pot';
   TC_PADDLEONLYSIDETONE                 = 'Paddle &only sidetone';
   TC_WINKEYERPORT                       = 'Winkeyer port';
   TC_KEYERMODE                          = 'Keyer mode';
   TC_SIDETONEFREQ                       = 'Sidetone freq.';
   TC_HANGTIME                           = 'Hang time';
   TC_IAMBICB                            = 'Iambic B';
   TC_IAMBICA                            = 'Iambic A';
   TC_ULTIMATIC                          = 'Ultimatic';
   TC_BUGMODE                            = 'Bug mode';
   TC_WEIGHTING                          = 'Weighting';
   TC_DITDAHRATIO                        = 'Dit/Dah ratio';
   TC_LEADIN                             = 'Lead-in time (*10 ms)';
   TC_TAIL                               = 'Tail time (*10 ms)';
   TC_FIRSTEXTENSION                     = 'First extension';
   TC_KEYCOMP                            = 'Keyer compensation';
   TC_PADDLESWITCHPOINT                  = 'Paddle switchpoint';

   // UTOTAL
   TC_QTCPENDING                         = 'QTC Pending';
   TC_ZONE                               = 'Zones';
   TC_PREFIX                             = 'Prefixes';
   TC_DXMULTS                            = 'DX Mults';
   TC_OBLASTS                            = 'Oblasts';
   TC_HQMULTS                            = 'HQ Mults';
   TC_DOMMULTS                           = 'Dom Mults';
   TC_QSOS                               = 'QSOs';
   TC_CWQSOS                             = 'CW QSOs';
   TC_SSBQSOS                            = 'SSB QSOs';
   TC_DIGQSOS                            = 'DIG QSOs';

   // UALTD
   TC_ENTERCALLTOBECHECKEDON             = 'Enter call to be checked on %s%s:';

   // LOGGRID
   TC_ALLSUN                             = 'All sun';
   TC_ALLDARK                            = 'All dark';

   // UMIXW
   TC_MIXW_CONNECTED                     = 'Connected';
   TC_MIXW_DISCONNECTED                  = 'Disconnected';

   // LOGWAE
   TC_INVALIDCALLSIGNINCALLWINDOW        = 'Invalid callsign in call window!!';
   TC_SORRYYOUALREADYHAVE10QTCSWITH      = 'Sorry, you already have 10 QTCs with %s';
   TC_NOQTCSPENDINGQRU                   = 'No QTCs pending, QRU.';
   TC_ISQRVFOR                           = 'Is %s QRV for %s?';

   // UREMMULTS
   TC_CLEANSWEEPCONGRATULATIONS          = 'CLEAN SWEEP!! CONGRATULATIONS!!';

   // CFGCMD
   TC_NETWORKTEST                        = 'Network Test';
   TC_MAXIMUMNUMBEROFREMINDERSEXCEEDED   = 'Maximum number of reminders exceeded!!';
   TC_INVALIDREMINDERTIME                = 'Invalid reminder time!!';
   TC_INVALIDREMINDERDATE                = 'Invalid reminder date!!';
   TC_TOOMANYTOTALSCOREMESSAGES          = 'Too many TOTAL SCORE MESSAGEs!!';
   TC_THEFIRSTCOMMANDINCONFIGFILEMUSTBE  = 'The first command in config file must be the MY CALL statement!!';

   // USYNTIME
   TC_MS                                 = ' ms';   //milliseconds

   // ULOGSEARCH
   TC_ENTRIESPERMS                       = '%u entries per %u ms';

   // ULOGCOMPARE
   TC_SIZEBYTES                          = 'Size, bytes';
   TC_RECORDS                            = 'Records';
   TC_MODIFIED                           = 'Modified';
   TC_TIMEDIFF                           = 'Time diff.';

   // POSTUNIT
   TC_MORETHAN50DIFFERENTHOURSINTHISLOG  = 'More than 50 different hours in this log!!';
   TC_TOOMANYCONTESTDATES                = 'Too many contest dates!!';

   // UGETSERVERLOG
   TC_FAILEDTORECEIVESERVERLOG           = 'Failed to receive server log.';

   // DLPORTIO
   TC_DLPORTIODRIVERISNOTINSTALLED       = 'DLPortIO error';

   // UCT1BOH
   TC_TIMEON                             = 'Time on';

   // ULOGCOMPARE
   TC_SERVERLOG                          = 'SERVER LOG';
   TC_LOCALLOG                           = 'LOCAL LOG';

   // UEDITMESSAGE
   TC_CTRL_A                             = 'Send this message on inactive radio';
   TC_CTRL_B                             = 'Identify ctrl-A message as a CQ';
   TC_CTRL_C                             = 'Start special command';
   TC_CTRL_D                             = 'Do not interrupt';
   TC_CTRL_E                             = 'Dah 73% of normal duration';
   TC_CTRL_F                             = 'Increase speed by 6%';
   TC_CTRL_K                             = 'Normal dah';
   TC_CTRL_L                             = 'Dit 140% of normal duration';
   TC_CTRL_N                             = 'Dah 113% of normal duration';
   TC_CTRL_O                             = 'Dah 127% of normal duration';
   TC_CTRL_P                             = 'Dit 60% of normal duration';
   TC_CTRL_Q                             = 'Dit 80% of normal duration';
   TC_CTRL_S                             = 'Decrease speed by 6%';
   TC_CTRL_V                             = 'Dit 120% of normal duration';
   TC_CTRL_X                             = 'Decrease weight by 0.03';
   TC_CTRL_Y                             = 'Increase weight by 0.03';
   TC_CTRL_SL                            = 'Normal dit';
   TC_QSO_NUMBER                         = 'QSO Number';
   TC_SALUTATION_AND_NAME_IF_KNOWN       = 'Salutation and name if known';
   TC_NAME_FROM_NAME_DATABASE            = 'Name from name database';
   TC_SEND_CHARACTERS_FROM_KEYBOARD      = 'Send characters from keyboard';
   TC_CALL_IN_CALL_WINDOW                = 'Call in Call Window';
   TC_RST_PROMPT                         = 'RST prompt';
   TC_SEND_CALLASSETBYMYCALLCOMMAND      = 'Send call as set by MY CALL command';
   TC_REPEATRSTSENT                      = 'Repeat RST sent';
   TC_VERSIONONSERVER                    = 'The last version on server';
   TC_THISVERSION2                       = 'This version';
   TC_DOWNLOADIT                         = 'Would you like to download the latest version?';
   TC_LIST_OF_COMMAND                    = 'List of commands';
   TC_EDITFUNCTIONKEY                    = 'Edit %s message';
   TC_SPLIT_WARN                         = 'Warning: You are in SPLIT MODE !!!';

   // FD Additions NY4I
   TC_IMPROPERTRANSMITTERCOUNT           = 'FD transmitters must be between 1 and 99.';
   TC_IMPROPERARRLFIELDDAYCLASS          = 'Field Day class must be A, B, C, D, E or F.';
   TC_IMPROPERWINTERFIELDDAYCLASS        = 'Winter Field Day class must be H, I, O or M.';
   TC_ARRLFIELDDAYIMPROPERDXEXCHANGE     = 'DX Station exchange must be "DX".';
   TC_RUNWARN                            = 'Another instance of TR4W is already running';
   TC_SHOW_PASSWORDS                     = 'Show passwords';
   TC_TOOLTIP_DISCOVERY                  = 'Discover radios on the network';
   TC_DISCOVER_NOT_AVAILABLE             = 'Network discovery is not available for radio %s';
   TC_DISCOVER_NONE_FOUND                = 'No radio of type %s found on the network';
   TC_DISCOVER_MULTI_FOUND               = 'More than one %s found; filled in the first.  All found:';
   TC_PORT_NOT_CONNECTED                 = '(not connected)';
   TC_SHOW_ALL_SERIAL_PORTS              = 'Show all serial ports';
   TC_DOWNLOADINGCTYDAT                  = 'Downloading CTY.DAT...';
   TC_DOWNLOADINGTRMASTERDTA             = 'Downloading TRMASTER.DTA...';
   TC_DOWNLOADINGPOTAPARKS               = 'Downloading POTA parks...';
   TC_HAMSCOREQUEUEINGFULLLOGRESYNC      = 'HamScore: queueing full log resync...';
   TC_LOGINCALLDOESLOOKLIKECALLSIGN      = 'Login call does not look like a callsign';
   TC_NOPOTAPARKSLOGGEDYETSESSION        = 'No POTA parks logged yet this session';
   TC_CWOFF                              = 'CW Off';
   TC_CANNOTOPENLOGFILE                  = 'Cannot open log file';
   TC_SCANNOTEDITEDHERE                  = '%s cannot be edited here.';
   TC_DEBUGMODECREATEDPREFIXESTXT        = 'debug mode created prefixes.txt';
   TC_POTAPARKSLOADED                    = 'POTA parks loaded';
   TC_POTAPARKSFILECOULDLOADED           = 'POTA parks file could not be loaded';
   TC_POTAPARKSDOWNLOADFAILED            = 'POTA parks download failed';
   TC_TRMASTERDTADOWNLOADEDRESTARTTR4WUS = 'TRMASTER.DTA downloaded -- restart TR4W to use it';
   TC_TRMASTERDTADOWNLOADFAILED          = 'TRMASTER.DTA download failed';
   TC_CTYDATDOWNLOADEDRELOADING          = 'CTY.DAT downloaded. Reloading...';
   TC_CTYDATRELOADEDSUCCESSFULLY         = 'CTY.DAT reloaded successfully.';
   TC_CTYDATDOWNLOADFAILED               = 'CTY.DAT download failed.';
   TC_ERRORPLAYINGVOICEMEMORY            = 'Error playing voice memory';
   TC_FLUSHINITIALEXCOMMANDEXECUTED      = 'FLUSHINITIALEX command is executed.';
   TC_AUTOSPOTENABLEDTESTMODEONLY        = 'AUTOSPOT is enabled - Test Mode Only';
   TC_HANDLOGMODETRUE                    = 'HAND LOG MODE = TRUE';
   TC_TRMASTERDTAS                       = 'TRMASTER.DTA : %s';
   TC_TR4WTIMEWARNING                    = 'TR4W Time Warning';
   TC_ERROROFFERINGCOMMANDERPROXYTCPPORT = 'Error offering Commander proxy TCP Port';
   TC_PTTVIACOMMANDSCTRLJOPTIONMUSTTRUEW = 'PTT VIA COMMANDS (CTRL-J) option must be true for WSJT-X use - Setting to true';
   TC_CANNOTDISABLESPLITTRANSMITSLICECRE = 'Cannot disable split -- the transmit slice was created on the radio. Turn it off in the SDR.';
   TC_SORRYUSEDUPALLREMINDERS            = 'Sorry, you have used up all your reminders!!';
   TC_INVALIDDATE                        = 'Invalid date!!';
   TC_ENOUGHMEMORYINITIALEXCHANGEARRAY   = 'Not enough memory for initial exchange array!!';
   TC_FINDINGZEROENDVISIBLEDUPESHEETLIST = 'Not finding zero at end visible dupesheet list!!';
   TC_QTCPROCESSTERMINATED               = 'QTC process terminated.';
   TC_QTCNUMBERILLEGALCHARACTERS         = 'QTC Number has illegal characters.';
   TC_NUMBERMESSAGESILLEGALCHARACTERS    = 'Number of messages has illegal characters.';
   TC_QTCPROCESSTERMINATEDINVALIDNUMBERM = 'QTC process terminated.  Invalid number of messages.';
   TC_IFOUNDCONTESTNAMEIDONOUNDERSTANDLO = 'I found a contest name I do no understand in your LOGCFG.DAT file.';
   TC_IDIDFINECONTESTNAMELOGCFGDATFILE   = 'I did not fine a contest name in your LOGCFG.DAT file.';
   TC_ARENEWENGLAND                      = 'Are you in New England?';
   TC_CWTIMERFIRED                       = 'CW Timer fired';
   TC_TESTRADIOINTERFACE                 = 'TEST RADIO INTERFACE';
   TC_UNABLESAVEDTAASCIIFILE             = 'Unable to save .DTA to ASCII file.';
   TC_SAVINGDTAFILEASCIIFILEPROCESSINGCE = 'Saving .DTA file to ASCII file.  Processing cell   ';
   TC_DATASUCCESSFULLYSAVEDASCIIFILE     = 'Data successfully saved to ASCII file.';
   TC_NOTRMASTERDTAFILEFOUND             = 'No TRMASTER.DTA file found.';
   TC_HITCOUNTHISTOGRAM050               = 'Hit count histogram for 0 to 50+ : ';
   TC_PLEASECHECKMULTINETWORK            = 'Please check multi network';
   TC_POSSIBLEDATALOSSMULTINETWORK       = 'Possible data loss on multi network.';
   TC_SELECTSPOTRETURNLEFTORRIGHTARROWSE = 'Select spot.  RETURN, left or right arrow to select.  ESCAPE to exit.';
   TC_ENTERCALLSIGNSPACEDUPECHECKALTHHEL = 'ENTER a callsign.  SPACE for dupecheck.  Alt-H for help.';
   TC_CONTINUEENTERINGCHARACTERSAUTOTERM = 'Continue entering characters.  Auto terminate active!!';
   TC_CONTINUEENTERINGCHARACTERSPRESSRET = 'Continue entering characters and press RETURN when done.';
   TC_ENTEREXCHANGEPRESSENTERLOGESCAPEAB = 'Enter exchange.  Press ENTER to log, ESCAPE to abort QSO.';
   TC_RELAYCONTROLPORTPADDLEPORT         = 'RELAY CONTROL PORT = PADDLE PORT';
   TC_LOCATIONFIELDEMPTY                 = 'LOCATION field is empty.';
   TC_PTTLOCKOUTTRUE                     = 'PTT LOCKOUT=TRUE';
   TC_PREFERENCESCOULDOPENEDS            = 'Preferences could not be opened (%s).';
   TC_THESEENTRIESWEREACCEPTEDBEENSAVED  = 'These entries were not accepted and have not been saved:';
   TC_TCISERVERCOULDOPENPORTDS           = 'The TCI server could not open port %d: %s';
   TC_KEYERNAMEDSALREADYEXISTS           = 'A keyer named "%s" already exists.';
   TC_SSTILLUSEDBYS                      = '"%s" is still used by: %s';
   TC_REMOVECLUSTERS                     = 'Remove the cluster "%s"?';
   { The DX cluster window, when the cluster library is empty.  Shown as a red
     label ABOVE the drop-down rather than as a greyed item inside it: a greyed
     combo item is still selectable, and one inside a drop-down is invisible
     until the operator opens it. }
   TC_NODXCLUSTERSDEFINED                = 'No DX clusters are defined yet -- click Configure to add one.';
   TC_CONFIGURE_ELLIPSIS                 = 'Configure...';
   { The DX Cluster page, when the shipped server directory is missing. Shown
     in place of the normal hint beside the Server drop-down, in red -- the
     normal hint promises a list, so leaving it there would be a lie. }
   TC_CLUSTERSERVERHINT                  = 'host:port, for example dxc.nc7j.com:7373.  The drop-down lists the servers in TRCLUSTER.DAT; you can also type one that is not on it.';
   TC_CLUSTERDIRMISSING                  = 'TRCLUSTER.DAT was not found beside the program, so the list is empty. Type the server as host:port, for example dxc.nc7j.com:7373.';
   TC_REMOVEROTATORS                     = 'Remove the rotator "%s"?';
   TC_LOGGINGRUNNINGSOTHERENOFILEOPEN    = 'Logging is not running, so there is no file to open.';
   TC_THERENOLOGFILEYETS                 = 'There is no log file yet at %s.';
   TC_EDITOR_EDIT                        = '&Edit';
   TC_EDITOR_OPENINEDITOR                = 'Open in text &editor';
   TC_EDITOR_EXPLORE                     = 'Explore';
   TC_EDITOR_COPY                        = '&Copy';
   TC_EDITOR_SELECTALL                   = 'Select &all';
   TC_EDITOR_SENDLOGTO                   = 'Send log to %s';
   TC_UPLOADCABRILLOTOSCP                = 'Do you want to upload your Cabrillo file to SuperChecklPartial?';

   { RC_ -- reachable from Pascal code }


   // UEDITMESSAGE
   RC_3830              = '3830 Score posting';   //4.51.8
   RC_3830_ARRL         = 'Submit ARRL Log';   //4.53.3
   RC_VIEWEDITLOG2      = 'View / Edit log';
   RC_CT1BOHIS2         = 'CT1BOH info screen';
   RC_BANDPLAN          = 'Band plan';
   RC_LISTOFMESS        = 'List of messages';
   RC_STATIONINFO       = 'Station information';
   RC_DUPECHECKOAR      = 'Dupe Check On Inactive Radio';
   RC_MEMPROGFUNC       = 'Memory program function';
   RC_PRESS_C           = 'Press &C to program a CQ function key.';
   RC_PRESS_E           = 'Press &E to program an exchange/search and pounce function key.';
   RC_PRESS_O           = 'Press &O to program the other non function key messages.';
   RC_SENDINGCW         = 'Sending CW from the keyboard. Use ENTER/Escape/F10 to exit.';
   RC_AUTOCQ2           = 'Auto-CQ';
   RC_PRESSMKYWTR       = 'Press the memory key you want to repeat:';
   RC_NUMBEROSOLT       = 'Number of milliseconds of listening time:';
   RC_WINCONTROL2       = 'Windows control';
   RC_TOOLS             = 'Tools';
   RC_BEACONSM          = 'Beacons monitor';
   RC_WINCONTROL        = 'Windows control';
   RC_SETTIMEZONE       = 'Set time zone';
   RC_PING              = 'Ping [SERVER ADDRESS]';
   RC_RUNSERVER         = 'Run TR4WSERVER';
   RC_DVKVOLCONTROL     = 'DVK volume control';
   RC_RECCONTROL        = 'Recording control';
   RC_CALCULATOR        = 'Calculator';
   RC_RESET_RADIO_PORTS = 'Reset Radio Ports';
   RC_TIMESYN           = 'Synchronize time on &all computers';
   RC_POSTNOW           = 'Post now';
   RC_GOTOGS            = 'Show scores';
   RC_MP3_RECENABLE     = 'Enable';
   RC_DELETESELSPOT     = 'Delete selected spot';
   RC_REMOVEALLSP       = 'Remove all spots';
   RC_SENDINRIG         = 'QSY Inactive Radio';
   RC_FILE              = 'File';
   RC_CLEARLOG          = 'Clear log';
   RC_IMPORT            = 'Import';
   RC_OPENLOGDIR        = 'Open log directory';
   RC_OPERATOR          = 'Operator';
   RC_CALLSIGN          = 'Callsign';
   RC_MODE              = 'Mode';
   RC_BAND              = 'Band';
   RC_EDIT_WORD         = '&Edit';
   RC_POSTSCORETOGS     = 'Post score';
   RC_EXPORT            = 'Export';
   RC_INIEXLIST         = 'Initial exchanges list';
   RC_TRLOGFORM         = 'TR Log format';
   RC_REPORTS           = 'Reports';
   RC_ALLCALLS          = 'All callsigns';
   RC_BANDCHANGES       = 'Band changes';
   RC_CONTLIST          = 'Continent List';
   RC_FCC               = 'First callsign worked in each country';
   RC_FCZ               = 'First callsign worked in each zone';
   RC_QSOBYCOUNTRY      = 'QSOs by country by band';
   RC_SCOREBYHOUR       = 'Score by hour';
   RC_SUMMARY           = 'Summary';
   RC_EXIT              = 'E&xit';
   RC_SETTINGS          = 'Settings';
   RC_OPTIONS           = 'Configuration commands';
   RC_PROGRAMMES        = 'Program messages';
   RC_CATANDCW          = 'CAT and CW Keying';
   RC_WINDOWS           = 'Windows';
   RC_BANDMAP           = 'Bandmap';
   RC_DUPESHEET         = 'Dupesheet';
   RC_FKEYS             = 'Function keys';
   RC_TRMASTER          = 'SCP';
   RC_REMMULTS          = 'Mults';   //4.72.3
   RC_RM_DEFAULT        = 'Default';
   RC_TELNET            = 'DX Cluster';
   RC_NETWORK           = 'Network';
   RC_INTERCOM          = 'Intercom';
   RC_STATIONS          = 'Stations';
   RC_MP3REC            = 'MP3 Recorder';
   RC_ALTP              = 'Open Fkeys';
   RC_ALTX              = 'Exit Program';
   RC_AUTOCQRESUME      = 'Auto-CQ resume';
   RC_DUPECHECK         = 'Dupe check';
   RC_EDIT              = 'SO1R-Edit or SO2R-SWAP';
   RC_BACKUPLOG         = 'Backup Log';
   RC_SWAPMULTVIEW      = 'Swap mult view';
   RC_INCNUMBER         = 'Increment number';
   RC_TOOGLEMB          = 'Toogle multiplier bell';
   RC_KILLCW            = 'Toggle CW';
   RC_SEARCHLOG         = 'Search log';
   RC_TRANSFREQ         = 'Transmit frequency';
   RC_AUTOCQ            = 'Auto-CQ';
   RC_TOOGLERIGS        = 'Toggle rigs';
   RC_CWSPEED           = 'CW speed';
   RC_SETSYSDT          = 'Set system date/time';
   RC_INITIALIZE        = 'Initialize QSO';
   RC_DELETELASTQSO     = 'Delete the last QSO';
   RC_INITIALEX         = 'Initial exchange';
   RC_TOOGLEST          = 'Toggle sidetone';
   RC_TOOGLEAS          = 'Toggle autosend';
   RC_BANDUP            = 'Band Up';
   RC_BANDDOWN          = 'Band Down';
   RC_SSBCWMODE         = 'SSB/CW mode';
   RC_SENDKEYBOARD      = 'Send Keyboard Input';
   RC_CLEARDUPES        = 'Clear dupesheet';
   RC_VIEWEDITLOG       = 'View / Edit log';
   RC_NOTE              = 'Note';
   RC_MISSMULTSREP      = 'Missing mults report';
   RC_QTCFUNCTIONS      = 'QTC functions';
   RC_RECALLLASTENT     = 'Recall last entry';
   RC_VIEWPAKSPOTS      = 'View packet spots';
   RC_EXECONFIGFILE     = 'Execute configuration file';
   RC_REFRESHBM         = 'Refresh bandmap';
   RC_CURSORINBM        = 'Cursor in bandmap window';
   RC_CURSORTELNET      = 'Cursor in DX Cluster window';
   RC_QSOWITHNOCW       = 'QSO with no CW';
   RC_CT1BOHIS          = 'CT1BOH info screen';
   RC_ADDBANDMAPPH      = 'Add bandmap place holder';
   RC_COMMANDS          = 'Commands';
   RC_FOCUSINMW         = 'Focus in main window';
   RC_TOGGLEINSERT      = 'Toggle insert mode';
   RC_ESCAPE            = 'Escape';
   RC_CWSPEEDUP         = 'CW Speed Up';
   RC_CWSPEEDDOWN       = 'CW Speed Down';
   RC_CWSPUPIR          = 'CW Speed Up for the inactive radio';
   RC_CWSPDNIR          = 'CW Speed Down for the inactive radio';
   RC_CQMODE            = 'CQ Mode';
   RC_SEARCHPOUNCE      = 'Search && pounce mode';
   RC_SENDSPOT          = 'Send spot';
   RC_RESCORE           = 'Rescore';
   RC_NET               = 'Net';
   RC_SENDMESSAGE       = 'Send message';
   RC_SYNLOG            = 'Compare and synchronize logs';
   RC_CLEARALLLOGS      = 'Clear all logs in network';
   RC_DOWNLOAD          = 'Download the latest CTY.DAT';
   RC_CONTENTS          = 'Contents';
   RC_ABOUT             = 'About';
   RC_DELETED           = 'Deleted';
   RC_SEARCH            = '&Search';
   RC_CONTESTNAMEIC     = 'C&ontest name in comment';
   RC_COMMENT           = 'Comment';
   RC_RECVQTC           = 'Receiving QTCs';
   RC_SYNLOG2           = 'Synchronize log';
   RC_GETSERVLOG        = '&Get server log';
   RC_RECVRECORDS       = 'Received records:';
   RC_SENDRECORDS       = 'Sent records:';
   RC_CREATEAUNL        = '&Create and use new log';
   RC_RECVBYTES         = 'Received bytes:';
   RC_RECVQSOS          = 'Received QSOs:';
   RC_SHOWSERVLOGC      = 'Show server log content';
   RC_DIFFINLOG         = 'Difference in logs';
   RC_DATE              = 'Date';
   RC_NAME              = 'Name';
   RC_PROGRMESS         = 'Program message';
   RC_MESSAGE           = 'Message';
   RC_CAPTION           = 'Caption';
   RC_IAQSLINT          = 'Auto QSL Interval (Increase)';
   RC_DAQSLINT          = 'Auto QSL Interval (Decrease)';
   RC_ADDINFO           = 'Additional information';
   RC_AI_QSONUMBER      = 'QSO number';
   RC_AI_CWSPEED        = 'CW Speed';
   RC_CLEARMSHEET       = 'Clear multsheet';
   RC_WIKI              = 'On-line documentation (in Russian)';
   RC_NET_CLDUPE        = 'Clear dupesheet in all logs';
   RC_NET_CLMULT        = 'Clear multsheet in all logs';
   RC_INC_TIME          = 'Increment time';
   RC_NOTES             = 'Notes';
   RC_DEVICEMANAGER     = 'Device Manager';
   RC_SHDX_CALLSIGN     = 'SH/DX [callsign]';
   RC_LOGIN             = 'Log in';
   RC_SYNCHRONIZE       = 'Synchronize';
   RC_COLORS            = 'Colors';
   RC_SEND_BUG          = 'Send bug report';
   RC_HOMEPAGE          = 'TR4W Home Page';
   RC_FREQUENCY         = 'Frequency';

   // FD Additions NY4I
   RC_SPLITOFF          = 'Set Split Mode Tx';
   RC_wkMode            = 'Re-initialize WinKeyer';   //4.60.1

   { Unprefixed -- the shared button captions }


   // UEDITMESSAGE
   CLOSE_WORD = 'Close';
   HELP_WORD  = 'Help';
   EXIT_WORD  = 'E&xit';

implementation

end.
