program tr4w;
{$IMPORTEDDATA OFF}
{$I src\tr4w.inc}

// VERSIONINFO PE resource (Windows Properties dialog: File version /
// Product name / Language / Copyright fields).  Generated per-build
// by FullBuild.ps1 / Write-VersionInfoResource with the language and
// version values from Version.pas substituted in.  Guarded so the
// Delphi 7 IDE -- which doesn't run FullBuild.ps1 -- compiles cleanly
// without the file present (just produces an EXE with blank version
// fields, same as the historical behaviour).  Command-line builds
// pass -DVERSIONINFO_RES to enable.
{$IFDEF VERSIONINFO_RES}
{$R tr4w_versioninfo.res}
{$ENDIF}

{ EVERY LANGUAGE, IN THE BINARY.

  Built by build\Make-LanguageRes.ps1 from i18n\tr4w_<lang>.po, one RCDATA
  resource named TR4W_<LANG> per language, read back by uEmbeddedTranslations.

  514 KB for sixteen languages, because only entries a HUMAN HAS REVIEWED are
  shipped: the run time refuses a fuzzy entry anyway, so they are dropped before
  they are ever embedded and the binary cannot carry unreviewed text.

  OUTSIDE THE VERSIONINFO_RES BLOCK, deliberately. It was written inside it
  first, and Build-App does not pass that define -- so the resource silently was
  not linked, FindResource returned 0, and the log said "none loaded" exactly as
  it would for a language nobody had translated. The language a build speaks has
  nothing to do with whether it carries version information. }
{$R res\tr4w_languages.res}

//https://groups.google.com/group/tr4w/feeds?hl=ru
uses
  Messages,
  MMSystem,
  Windows,
  SysUtils,
  MainUnit in 'src\MainUnit.pas',
  BeepUnit in 'src\trdos\BeepUnit.pas',
  CFGCMD in 'src\trdos\CfgCmd.pas',
  CFGDEF in 'src\trdos\CFGDEF.PAS',
  FCONTEST in 'src\trdos\FCONTEST.PAS',
  LogCfg in 'src\trdos\LogCfg.pas',
  LogCW in 'src\trdos\LogCW.pas',
  LogDom in 'src\trdos\LOGDOM.PAS',
  LogDupe in 'src\trdos\LOGDUPE.PAS',
  LOGDVP in 'src\trdos\LOGDVP.PAS',
  LogEdit in 'src\trdos\LOGEDIT.PAS',
  LogGrid in 'src\trdos\LOGGRID.PAS',
  LogK1EA in 'src\trdos\LOGK1EA.PAS',
  LogNet in 'src\trdos\LOGNET.PAS',
  LogPack in 'src\trdos\LOGPACK.PAS',
  LogRadio in 'src\trdos\LOGRADIO.PAS',
  LogSCP in 'src\trdos\LOGSCP.PAS',
  LogStuff in 'src\trdos\LOGSTUFF.PAS',
  LOGWAE in 'src\trdos\LOGWAE.PAS',
  LogWind in 'src\trdos\LOGWIND.PAS',
  Tree in 'src\trdos\tree.pas',
  ZoneCont in 'src\trdos\ZONECONT.PAS',
  LOGSUBS2 in 'src\trdos\LOGSUBS2.PAS',
  LOGSUBS1 in 'src\trdos\LOGSUBS1.PAS',
  LOGSend in 'src\trdos\LogSend.pas',
  uCT1BOH in 'src\uCT1BOH.pas',
  PostUnit in 'src\trdos\PostUnit.PAS',
  uCabrilloFormat in 'src\uCabrilloFormat.pas',
  uCabrilloExchange in 'src\uCabrilloExchange.pas',
  uADIFExchange in 'src\uADIFExchange.pas',
  uInputQuery in 'src\uInputQuery.pas',
  uNewContestForm in 'src\ui\lcl\uNewContestForm.pas' {frmNewContest},
  uTextFitAudit in 'src\ui\lcl\uTextFitAudit.pas',
  uNewContest in 'src\uNewContest.pas',
  uRadioPolling in 'src\uRadioPolling.pas',
  uEditQSO in 'src\uEditQSO.pas',
  uLogSearch in 'src\uLogSearch.pas',
  uBeacons in 'src\uBeacons.pas',
  uNetFraming in 'src\uNetFraming.pas',
  uNet in 'src\uNet.pas',
  uNetClient in 'src\uNetClient.pas',
  uTotal in 'src\uTotal.pas',
  uMaster in 'src\uMaster.pas',
  uRemMults in 'src\uRemMults.pas',
  uDupesheet in 'src\uDupesheet.pas',
  uSendSpot in 'src\uSendSpot.pas',
  uSendKeyboard in 'src\uSendKeyboard.pas',
  uRadio12 in 'src\uRadio12.pas',
  uFunctionKeys in 'src\uFunctionKeys.pas',
  uinet in 'src\uinet.pas',
  uDXClusterClient in 'src\uDXClusterClient.pas',
  uDXSpotParse in 'src\uDXSpotParse.pas',
  uTelnet in 'src\uTelnet.pas',
  uBandmap in 'src\uBandmap.pas',
  uBandMapView in 'src\uBandMapView.pas',
  uBandMapForm in 'src\ui\lcl\uBandMapForm.pas',
  uPanadapterForm in 'src\ui\lcl\uPanadapterForm.pas',
  uPanadapterRestore in 'src\uPanadapterRestore.pas',
  uStationsForm in 'src\ui\lcl\uStationsForm.pas',
  uDomainState in 'src\domain\uDomainState.pas',
  uWSJTXState in 'src\domain\uWSJTXState.pas',
  uRadioState in 'src\domain\uRadioState.pas',
  uKeyerState in 'src\domain\uKeyerState.pas',
  uLogSchema in 'src\domain\uLogSchema.pas',
  uLogDatabase in 'src\domain\uLogDatabase.pas',
  uStateBridge in 'src\ui\lcl\uStateBridge.pas',
  uFlowGrid in 'src\ui\lcl\uFlowGrid.pas',
  uDupeSheetForm in 'src\ui\lcl\uDupeSheetForm.pas',
  uMasterForm in 'src\ui\lcl\uMasterForm.pas',
  uPostScoresForm in 'src\ui\lcl\uPostScoresForm.pas',
  uHamScoreForm in 'src\ui\lcl\uHamScoreForm.pas',
  uIntercomForm in 'src\ui\lcl\uIntercomForm.pas',
  uMP3RecorderForm in 'src\ui\lcl\uMP3RecorderForm.pas',
  uRadioPanelForm in 'src\ui\lcl\uRadioPanelForm.pas',
  uNetworkForm in 'src\ui\lcl\uNetworkForm.pas',
  uRemMultsForm in 'src\ui\lcl\uRemMultsForm.pas',
  uAppInputHooks in 'src\ui\lcl\uAppInputHooks.pas',
  uFileView in 'src\uFileView.pas',
  uAutoCQ in 'src\uAutoCQ.pas',
  uCAT in 'src\uCAT.pas',
  // The radio-configuration layer.  Nothing calls these yet -- the FMX
  // preferences dialog is the caller -- but they are listed so the compiler
  // checks them against the live CFGCA/CAT surface on every build.
  uRotatorBase in 'src\rotatorFactory\uRotatorBase.pas',
  uRotatorControl in 'src\uRotatorControl.pas',
  uRotatorRegistry in 'src\rotatorFactory\uRotatorRegistry.pas',
  uRotatorYaesu in 'src\rotatorFactory\uRotatorYaesu.pas',
  uRotatorOrion in 'src\rotatorFactory\uRotatorOrion.pas',
  uRotatorDCU1 in 'src\rotatorFactory\uRotatorDCU1.pas',
  uRotatorAlfaSpid in 'src\rotatorFactory\uRotatorAlfaSpid.pas',
  uRotatorPSTRotator in 'src\rotatorFactory\uRotatorPSTRotator.pas',
  uSettingsRegistry in 'src\uSettingsRegistry.pas',
  uSettingsLegacy in 'src\uSettingsLegacy.pas',
  uAppPaths in 'src\uAppPaths.pas',
  uSettingsCaptions in 'src\uSettingsCaptions.pas',
  uSettingsDeclarations in 'src\uSettingsDeclarations.pas',
  uRadioConfigStore in 'src\uRadioConfigStore.pas',
  uKeyerConfigStore in 'src\uKeyerConfigStore.pas',
  uKeyerConfigApply in 'src\uKeyerConfigApply.pas',
  uUDPBroadcastConfig in 'src\uUDPBroadcastConfig.pas',
  uUDPBroadcaster in 'src\uUDPBroadcaster.pas',
  uWindowLayoutStore in 'src\uWindowLayoutStore.pas',
  uTR4WConfigFile in 'src\uTR4WConfigFile.pas',
  uRadioConfigLegacyMap in 'src\uRadioConfigLegacyMap.pas',
  uRadioConfigApply in 'src\uRadioConfigApply.pas',
  // The FMX twins were DELETED 2026-08-17, at the start of the Win32-to-LCL
  // migration.  They were never in an FPC build -- FMX has no FPC compiler --
  // so under the decided toolchain they were code nothing compiled, and had
  // already drifted from the LCL forms that replaced them.  Deleting them here
  // rather than per-form means no conversion has to ask whether it owes a twin.
  // The LCL set is in the {$IFDEF FPC} block below.
  uAccelerators in 'src\uAccelerators.pas',
  uMainWindowProc in 'src\uMainWindowProc.pas',
  uDialogs in 'src\uDialogs.pas',
  Version in 'src\Version.pas',
  uTR4WStrings in 'src\uTR4WStrings.pas',
  VC in 'src\VC.pas',
  uCommctrl in 'src\uCommctrl.pas',
  uGradient in 'src\uGradient.pas',
  uMessages in 'src\uMessages.pas',
  uWinManager in 'src\uWinManager.pas',
  uCbrSum in 'src\uCbrSum.pas',
  uQTCR in 'src\uQTCR.pas',
  uQTCS in 'src\uQTCS.pas',
  LPT in 'src\LPT.pas',
  uGetServerLog in 'src\uGetServerLog.pas',
  TF in 'src\TF.pas',
  uFreqTimeFormat in 'src\uFreqTimeFormat.pas',
  uLogEdit in 'src\uLogEdit.pas',
  uIntercom in 'src\uIntercom.pas',
  uLogCompare in 'src\uLogCompare.pas',
  uMixW in 'src\uMixW.pas',
  uCallsigns in 'src\uCallsigns.pas',
  uSpots in 'src\uSpots.pas',
  uSpotAge in 'src\uSpotAge.pas',
  uClusterTokens in 'src\uClusterTokens.pas',
  uGetScores in 'src\uGetScores.pas',
  uStations in 'src\uStations.pas',
  uAltD in 'src\uAltD.pas',
  uWinKey in 'src\uWinKey.pas',
  uLPTPortEnumerator in 'src\uLPTPortEnumerator.pas',
  uPrefsSearch in 'src\uPrefsSearch.pas',
  uConfigValues in 'src\uConfigValues.pas',
  uCrashLog in 'src\uCrashLog.pas',
  uCrashLogLCL in 'src\ui\lcl\uCrashLogLCL.pas',
  uCFG in 'src\uCFG.pas',
  uCRC32 in 'src\uCRC32.pas',
  uCRC16 in 'src\uCRC16.pas',
  uSpectrumTypes in 'src\uSpectrumTypes.pas',
  uPanadapterView in 'src\uPanadapterView.pas',
  uMP3Recorder in 'src\uMP3Recorder.pas',
  uAltP in 'src\uAltP.pas',
  uEditMessage in 'src\uEditMessage.pas',
  uCheckLatestVersion in 'src\uCheckLatestVersion.pas',
  uErmak in 'src\uErmak.pas',
  uProcessCommand in 'src\uProcessCommand.pas',
  uMults in 'src\uMults.pas',
  HtmlHelp in 'src\HtmlHelp.pas',
  uSSL in 'src\uSSL.pas',
  uIO in 'src\uIO.pas',
  uBMCF in 'src\uBMCF.pas',
  uCTYDAT in 'src\uCTYDAT.PAS',
  uCallSignRoutines in 'src\uCallSignRoutines.pas',
  uSynTime in 'src\uSynTime.pas',
  uMMTTY in 'src\uMMTTY.pas',
  uProfiler in 'src\uProfiler.pas',
  uMessagesList in 'src\uMessagesList.pas',
  uRussiaOblasts in 'src\uRussiaOblasts.pas',
  uMenu in 'src\uMenu.pas',
  utils_net in 'src\utils\utils_net.pas',
  utils_hw in 'src\utils\utils_hw.pas',
  uAnsiStr in 'src\utils\uAnsiStr.pas',
  uFileText in 'src\utils\uFileText.pas',
  uPlatformProcess in 'src\utils\uPlatformProcess.pas',
  uRegex in 'src\utils\uRegex.pas',
  uWin32Compat in 'src\utils\uWin32Compat.pas',
  uHostedFormWindows in 'src\utils\uHostedFormWindows.pas',
  // The LCL side of hosting a toolkit in TR4W's own loop.  FPC-only:
  // Delphi cannot compile the LCL, just as FPC cannot compile FMX.
  uLCLCoexist in 'src\ui\lcl\uLCLCoexist.pas',
  uLCLTranslate in 'src\ui\lcl\uLCLTranslate.pas',
  uEmbeddedTranslations in 'src\ui\lcl\uEmbeddedTranslations.pas',
  uLCLFormHelpers in 'src\ui\lcl\uLCLFormHelpers.pas',
  uSettingsBinding in 'src\ui\lcl\uSettingsBinding.pas',
  uUDPDestinationEditForm in 'src\ui\lcl\uUDPDestinationEditForm.pas',
  uAltDForm in 'src\ui\lcl\uAltDForm.pas',
  uLogCompareForm in 'src\ui\lcl\uLogCompareForm.pas',
  uServerLogForm in 'src\ui\lcl\uServerLogForm.pas',
  uCT1BOHForm in 'src\ui\lcl\uCT1BOHForm.pas',
  uBeaconsForm in 'src\ui\lcl\uBeaconsForm.pas',
  uEditQSOForm in 'src\ui\lcl\uEditQSOForm.pas',
  uPanelUpdate in 'src\uPanelUpdate.pas',
  uMainThreadWork in 'src\uMainThreadWork.pas',
  uFlasher in 'src\ui\lcl\uFlasher.pas',
  uLPTForm in 'src\ui\lcl\uLPTForm.pas',
  uAboutForm in 'src\ui\lcl\uAboutForm.pas',
  uAltPForm in 'src\ui\lcl\uAltPForm.pas',
  uCabrilloSummaryForm in 'src\ui\lcl\uCabrilloSummaryForm.pas',
  uFileViewForm in 'src\ui\lcl\uFileViewForm.pas',
  uQTCSendForm in 'src\ui\lcl\uQTCSendForm.pas',
  uQTCReceiveForm in 'src\ui\lcl\uQTCReceiveForm.pas',
  uFunctionKeysForm in 'src\ui\lcl\uFunctionKeysForm.pas',
  uBandPlanForm in 'src\ui\lcl\uBandPlanForm.pas',
  uLegacyIniPrompt in 'src\ui\lcl\uLegacyIniPrompt.pas',
  uIniRetireForm in 'src\ui\lcl\uIniRetireForm.pas',
  uWinManagerForm in 'src\ui\lcl\uWinManagerForm.pas',
  uMessagesListForm in 'src\ui\lcl\uMessagesListForm.pas',
  uEditMessageForm in 'src\ui\lcl\uEditMessageForm.pas',
  uSendKeyboardForm in 'src\ui\lcl\uSendKeyboardForm.pas',
  uAutoCQForm in 'src\ui\lcl\uAutoCQForm.pas',
  uSendSpotForm in 'src\ui\lcl\uSendSpotForm.pas',
  uInputQueryForm in 'src\ui\lcl\uInputQueryForm.pas',
  uProgramMessageForm in 'src\ui\lcl\uProgramMessageForm.pas',
  uKeyerEditForm in 'src\ui\lcl\uKeyerEditForm.pas',
  uRadioEditForm in 'src\ui\lcl\uRadioEditForm.pas',
  uMainForm in 'src\ui\lcl\uMainForm.pas',
  uPrefsForm in 'src\ui\lcl\uPrefsForm.pas',
  uJSON in 'src\utils\uJSON.pas',
  uHTTPDownload in 'src\utils\uHTTPDownload.pas',
  utils_text in 'src\utils\utils_text.pas',
  utils_math in 'src\utils\utils_math.pas',
  utils_file in 'src\utils\utils_file.pas',
  uWinTimer in 'src\utils\uWinTimer.pas',
  uWSJTX in 'src\uWSJTX.pas',
  uHamScore in 'src\uHamScore.pas',
  uExchangeBuilder in 'src\uExchangeBuilder.pas',
  uGridLookup in 'src\uGridLookup.pas',
  Log4D in 'include\Log4D.pas',
  uFactoryRadioBase in 'src\radioFactory\uFactoryRadioBase.pas',
  uSerialPort in 'src\uSerialPort.pas',
  uRadioFactory in 'src\radioFactory\uRadioFactory.pas',
  uRadioElecraftK4 in 'src\radioFactory\uRadioElecraftK4.pas',
  uRadioElecraftSerial in 'src\radioFactory\uRadioElecraftSerial.pas',
  uRadioYaesuASCII in 'src\radioFactory\uRadioYaesuASCII.pas',
  uRadioYaesuFTDX10 in 'src\radioFactory\uRadioYaesuFTDX10.pas',
  uRadioYaesuBinary in 'src\radioFactory\uRadioYaesuBinary.pas',
  uRadioYaesuFT1000MP in 'src\radioFactory\uRadioYaesuFT1000MP.pas',
  uRadioYaesuFT817Group in 'src\radioFactory\uRadioYaesuFT817Group.pas',
  uRadioYaesuFT817 in 'src\radioFactory\uRadioYaesuFT817.pas',
  uRadioYaesuFT818 in 'src\radioFactory\uRadioYaesuFT818.pas',
  uRadioYaesuFT857 in 'src\radioFactory\uRadioYaesuFT857.pas',
  uRadioYaesuFT897 in 'src\radioFactory\uRadioYaesuFT897.pas',
  uRadioYaesuFT847 in 'src\radioFactory\uRadioYaesuFT847.pas',
  uRadioYaesuFT990Group in 'src\radioFactory\uRadioYaesuFT990Group.pas',
  uRadioYaesuFT990 in 'src\radioFactory\uRadioYaesuFT990.pas',
  uRadioYaesuFT1000 in 'src\radioFactory\uRadioYaesuFT1000.pas',
  uRadioYaesuFT840Group in 'src\radioFactory\uRadioYaesuFT840Group.pas',
  uRadioYaesuFT840 in 'src\radioFactory\uRadioYaesuFT840.pas',
  uRadioYaesuFT890 in 'src\radioFactory\uRadioYaesuFT890.pas',
  uRadioYaesuFT900 in 'src\radioFactory\uRadioYaesuFT900.pas',
  uRadioYaesuFT920 in 'src\radioFactory\uRadioYaesuFT920.pas',
  uRadioYaesuFT100 in 'src\radioFactory\uRadioYaesuFT100.pas',
  uRadioYaesuFT747 in 'src\radioFactory\uRadioYaesuFT747.pas',
  uRadioYaesuFT767 in 'src\radioFactory\uRadioYaesuFT767.pas',
  uRadioYaesuFT991 in 'src\radioFactory\uRadioYaesuFT991.pas',
  uRadioYaesuFTDX101 in 'src\radioFactory\uRadioYaesuFTDX101.pas',
  uRadioYaesuFT710 in 'src\radioFactory\uRadioYaesuFT710.pas',
  uRadioYaesuFTX1F in 'src\radioFactory\uRadioYaesuFTX1F.pas',
  uRadioYaesuFT891 in 'src\radioFactory\uRadioYaesuFT891.pas',
  uRadioYaesuASCIILegacy in 'src\radioFactory\uRadioYaesuASCIILegacy.pas',
  uRadioYaesuFT450 in 'src\radioFactory\uRadioYaesuFT450.pas',
  uRadioYaesuFT950 in 'src\radioFactory\uRadioYaesuFT950.pas',
  uRadioYaesuFT1200 in 'src\radioFactory\uRadioYaesuFT1200.pas',
  uRadioYaesuFT2000 in 'src\radioFactory\uRadioYaesuFT2000.pas',
  uRadioYaesuFTDX3000 in 'src\radioFactory\uRadioYaesuFTDX3000.pas',
  uRadioYaesuFTDX5000 in 'src\radioFactory\uRadioYaesuFTDX5000.pas',
  uRadioYaesuFTDX9000 in 'src\radioFactory\uRadioYaesuFTDX9000.pas',
  uRadioFlexCAT in 'src\radioFactory\uRadioFlexCAT.pas',
  uRadioFlex6000 in 'src\radioFactory\uRadioFlex6000.pas',
  uRadioElecraftK3 in 'src\radioFactory\uRadioElecraftK3.pas',
  uRadioElecraftK2 in 'src\radioFactory\uRadioElecraftK2.pas',
  uRadioElecraftKX3 in 'src\radioFactory\uRadioElecraftKX3.pas',
  uRadioKenwoodLAN in 'src\radioFactory\uRadioKenwoodLAN.pas',
  uWebSocketFraming in 'src\uWebSocketFraming.pas',
  uWebSocketClient in 'src\uWebSocketClient.pas',
  uWebSocketServer in 'src\uWebSocketServer.pas',
  uTCIProtocol in 'src\uTCIProtocol.pas',
  uTCIServer in 'src\uTCIServer.pas',
  uRadioTCI in 'src\radioFactory\uRadioTCI.pas',
  uRadioKenwoodTS890 in 'src\radioFactory\uRadioKenwoodTS890.pas',
  uRadioKenwoodTS990 in 'src\radioFactory\uRadioKenwoodTS990.pas',
  uIcomNetworkTypes in 'src\uIcomNetworkTypes.pas',
  uIcomNetworkTransport in 'src\uIcomNetworkTransport.pas',
  uIcomNetworkDiscovery in 'src\uIcomNetworkDiscovery.pas',
  uRadioIcomBase in 'src\radioFactory\uRadioIcomBase.pas',
  uRadioIcom9700 in 'src\radioFactory\uRadioIcom9700.pas',
  uRadioIcom7610 in 'src\radioFactory\uRadioIcom7610.pas',
  uRadioIcom7300 in 'src\radioFactory\uRadioIcom7300.pas',
  uRadioIcom705 in 'src\radioFactory\uRadioIcom705.pas',
  uRadioIcom7110 in 'src\radioFactory\uRadioIcom7110.pas',
  uRadioIcom7300MK2 in 'src\radioFactory\uRadioIcom7300MK2.pas',
  uRadioIcom7600 in 'src\radioFactory\uRadioIcom7600.pas',
  uRadioIcom7760 in 'src\radioFactory\uRadioIcom7760.pas',
  uRadioIcom7850 in 'src\radioFactory\uRadioIcom7850.pas',
  uRadioIcom7851 in 'src\radioFactory\uRadioIcom7851.pas',
  uRadioIcom905 in 'src\radioFactory\uRadioIcom905.pas',
  GetWinVersionInfo in 'src\GetWinVersionInfo.pas',
  uSuperCheckPartialFileUpload in 'src\uSuperCheckPartialFileUpload.pas',
  uHamLibDirect in 'src\uHamLibDirect.pas',
  uRadioHamLibDirect in 'src\radioFactory\uRadioHamLibDirect.pas',
  uExternalLoggerBase in 'src\uExternalLoggerBase.pas',
  uExternalLogger in 'src\uExternalLogger.pas',
  uExternalLoggerFactory in 'src\uExternalLoggerFactory.pas',
  // uExternalLoggerManager uses Generics.Collections (Delphi 2009+) - not Delphi 7 IDE compatible
  //uExternalLoggerManager in 'src\uExternalLoggerManager.pas',
  uDXLabPathfinder in 'src\uDXLabPathfinder.pas',
  uYCCCSO2R in 'src\uYCCCSO2R.pas',
  uCWKeyerBase in 'src\uCWKeyerBase.pas',
  uCWKeyerCAT in 'src\uCWKeyerCAT.pas',
  uCWKeyerWinKey in 'src\uCWKeyerWinKey.pas',
  uCWKeyerYCCC in 'src\uCWKeyerYCCC.pas',
  uCWKeyerCPU in 'src\uCWKeyerCPU.pas',
  uRadioFlexAPI in 'src\radioFactory\uRadioFlexAPI.pas',
  uRadioBand in 'src\radioFactory\uRadioBand.pas',
  uBandLookup in 'src\uBandLookup.pas',
  ComPortEnumerator in 'src\ComPortEnumerator.pas',
  uRadioIcom7100 in 'src\radioFactory\uRadioIcom7100.pas',
  uRadioIcom718 in 'src\radioFactory\uRadioIcom718.pas',
  uRadioIcomLegacy in 'src\radioFactory\uRadioIcomLegacy.pas',
  uRadioIcomReadLimited in 'src\radioFactory\uRadioIcomReadLimited.pas',
  uRadioIcomModern in 'src\radioFactory\uRadioIcomModern.pas',
  uRadioHamLibOnly in 'src\radioFactory\uRadioHamLibOnly.pas',
  uCWFraming in 'src\radioFactory\uCWFraming.pas',
  uK4Spectrum in 'src\radioFactory\uK4Spectrum.pas',
  uK4SpectrumThread in 'src\radioFactory\uK4SpectrumThread.pas',
  uIcomScope in 'src\radioFactory\uIcomScope.pas',
  uRadioKYBase in 'src\radioFactory\uRadioKYBase.pas',
  uRadioElecraftBase in 'src\radioFactory\uRadioElecraftBase.pas',
  uRadioKenwoodBase in 'src\radioFactory\uRadioKenwoodBase.pas',
  uRadioIcom78 in 'src\radioFactory\uRadioIcom78.pas',
  uRadioIcom707 in 'src\radioFactory\uRadioIcom707.pas',
  uRadioIcom725 in 'src\radioFactory\uRadioIcom725.pas',
  uRadioIcom726 in 'src\radioFactory\uRadioIcom726.pas',
  uRadioIcom728 in 'src\radioFactory\uRadioIcom728.pas',
  uRadioIcom729 in 'src\radioFactory\uRadioIcom729.pas',
  uRadioIcom735 in 'src\radioFactory\uRadioIcom735.pas',
  uRadioIcom736 in 'src\radioFactory\uRadioIcom736.pas',
  uRadioIcom737 in 'src\radioFactory\uRadioIcom737.pas',
  uRadioIcom738 in 'src\radioFactory\uRadioIcom738.pas',
  uRadioIcom746 in 'src\radioFactory\uRadioIcom746.pas',
  uRadioIcom746PRO in 'src\radioFactory\uRadioIcom746PRO.pas',
  uRadioIcom756 in 'src\radioFactory\uRadioIcom756.pas',
  uRadioIcom756PRO in 'src\radioFactory\uRadioIcom756PRO.pas',
  uRadioIcom756PROII in 'src\radioFactory\uRadioIcom756PROII.pas',
  uRadioIcom756PROIII in 'src\radioFactory\uRadioIcom756PROIII.pas',
  uRadioIcom761 in 'src\radioFactory\uRadioIcom761.pas',
  uRadioIcom765 in 'src\radioFactory\uRadioIcom765.pas',
  uRadioIcom775 in 'src\radioFactory\uRadioIcom775.pas',
  uRadioIcom781 in 'src\radioFactory\uRadioIcom781.pas',
  uRadioIcom910 in 'src\radioFactory\uRadioIcom910.pas',
  uRadioIcom970D in 'src\radioFactory\uRadioIcom970D.pas',
  uRadioIcom7200 in 'src\radioFactory\uRadioIcom7200.pas',
  uRadioIcom7410 in 'src\radioFactory\uRadioIcom7410.pas',
  uRadioIcom9100 in 'src\radioFactory\uRadioIcom9100.pas',
  uRadioTenTecOmni6 in 'src\radioFactory\uRadioTenTecOmni6.pas',
  uRadioTenTecOrion in 'src\radioFactory\uRadioTenTecOrion.pas',
  uRadioIcom7700 in 'src\radioFactory\uRadioIcom7700.pas',
  uRadioIcom7800 in 'src\radioFactory\uRadioIcom7800.pas',
  uRadioRegistry in 'src\radioFactory\uRadioRegistry.pas',
  uRadioKenwoodSerial in 'src\radioFactory\uRadioKenwoodSerial.pas',
  uRadioKenwoodTS570 in 'src\radioFactory\uRadioKenwoodTS570.pas',
  uRadioKenwoodTS140 in 'src\radioFactory\uRadioKenwoodTS140.pas',
  uRadioKenwoodTS440 in 'src\radioFactory\uRadioKenwoodTS440.pas',
  uRadioKenwoodTS450 in 'src\radioFactory\uRadioKenwoodTS450.pas',
  uRadioKenwoodTS480 in 'src\radioFactory\uRadioKenwoodTS480.pas',
  uRadioKenwoodTS590 in 'src\radioFactory\uRadioKenwoodTS590.pas',
  uRadioKenwoodTS690 in 'src\radioFactory\uRadioKenwoodTS690.pas',
  uRadioKenwoodTS850 in 'src\radioFactory\uRadioKenwoodTS850.pas',
  uRadioKenwoodTS870 in 'src\radioFactory\uRadioKenwoodTS870.pas',
  uRadioKenwoodTS940 in 'src\radioFactory\uRadioKenwoodTS940.pas',
  uRadioKenwoodTS950 in 'src\radioFactory\uRadioKenwoodTS950.pas',
  uRadioKenwoodTS2000 in 'src\radioFactory\uRadioKenwoodTS2000.pas',
  uIcomCIV in 'src\uIcomCIV.pas',
  // uRadioManager uses Generics.Collections (Delphi 2009+) - not Delphi 7 IDE compatible
  //uRadioManager in 'src\radioFactory\uRadioManager.pas',
  // DELETED 2026-08-28: uRemMults_DOM/DX/Zone, uDXSSpotsFilter,
  // uSpotsFilter and uMultsFrequencies. Commented out of this uses clause
  // since the initial commit, so never compiled, and with no live reference
  // anywhere -- the notes here recorded why: one set depends on a
  // Country9.pas that was never in the repo, one is unfinished, one is
  // orphaned. Six Win32 dialog procedures, 794 lines.
  uMakeHelpFile in 'src\uMakeHelpFile.pas',
  uLogConfig in 'src\uLogConfig.pas',
  uPOTAParks in 'src\uPOTAParks.pas',
  uPendingCounties in 'src\uPendingCounties.pas',
  uCTYUpdate in 'src\uCTYUpdate.pas',
  uTRMasterUpdate in 'src\uTRMasterUpdate.pas',
  uAppStrings in 'src\uAppStrings.pas',
  uCabrilloHeader in 'src\uCabrilloHeader.pas',
  // D12: transitively-compiled units added so project-wide file searches see them
  // (they were pulled in via other units' uses clauses but never listed here).
  uADIF in 'src\uADIF.pas',
  uCabrillo in 'src\uCabrillo.pas',
  uCallCompress in 'src\uCallCompress.pas',
  uFlexRadioUtils in 'src\radioFactory\uFlexRadioUtils.pas',
  uGridDistance in 'src\uGridDistance.pas',
  uK4Discovery in 'src\uK4Discovery.pas',
  uFlexDiscovery in 'src\radioFactory\uFlexDiscovery.pas',
  uStrSearch in 'src\uStrSearch.pas',
  NetworkMessageUtils in 'src\utils\NetworkMessageUtils.pas',
  // THE PROGRAM BODY.  Everything this file used to run lives in here, where
  // a search of src\ can find it.  See the unit header for why.
  uTelnetForm in 'src\ui\lcl\uTelnetForm.pas',
  uMMTTYForm in 'src\ui\lcl\uMMTTYForm.pas',
  uProgramMain in 'src\uProgramMain.pas';
  //cty in 'src\cty.pas';  // Excluded: unit name 'cty' conflicts with global variable 'CTY' from uCTYDAT

{ THE PROJECT RESOURCE -- tr4w.res, written by Lazarus from the .lpi.

  Carries MAINICON, the application icon, which is loaded by name at four sites
  (uProgramMain's window class, uDialogs twice, uNet's list icon). Lazarus names
  its project icon MAINICON as well, which is why moving the icon off the
  Delphi-era resource needed no code change at all.

  This replaced the res\tr4w_eng.res link on 2026-08-29 -- named without its
  $R braces, because a directive inside a brace comment closes the comment and
  the compiler then reads the prose as code. That file held seven
  resources and only the icon was still reached: dialogs 46, 66 and 73 had no
  loader left once dialog 73 became a designed form, ACCELERATOR 'T' was
  replaced by the Pascal table in uAccelerators, and nothing ever called
  LoadBitmap for BITMAP 853. It had no CURSOR resource -- every LoadCursor in
  the tree asks Windows for a stock one.

  Before that it was one of ELEVEN links, ten of them guarded by an IFDEF on
  LANG_<xxx> -- written here without its braces, because a directive inside a
  brace comment closes the comment. No build had defined those symbols since the
  compile-time language matrix was retired, so ten could not compile; and the
  eleventh was guarded on LANG_ENG, which tr4w.inc derives ONLY when none of the
  other ten is set. -dLANG_RUS would have linked no icon at all. }
{$R *.res}

{ The manifest stays hand-kept and separate: the build VERIFIES it -- "manifest
  verified in the binary (parses, visual styles declared)" -- and the .lpi
  checkbox offers less control over the content. }
{$R 'Win11.res'}

begin
   RunTR4W;
end.
