"""Generate the resourcestring unit from the English constant tables.

`tr4w/src/lang/tr4w_consts_eng.pas` is a `{$INCLUDE}` fragment of `const`
declarations, one per language, selected by a LANG_xxx define at compile time.
The replacement is ONE binary with `resourcestring`, translated at run time from
a .po (NY4I, 2026-08-13). This writes that unit.

WHAT IT EMITS, AND WHAT IT LEAVES BEHIND
----------------------------------------
  TC_*  all of them -- these are consumed from Pascal.

  RC_*  ONLY those a Pascal source actually references. The rest are captions
        inside `res/Tr4w.rc`, whose text reaches the screen through the compiled
        .RES, not through this constant -- so declaring a resourcestring for one
        would translate nothing. Measured 2026-08-26 across 250 RC_:
            10 code only, 153 both, 78 .rc only, 9 referenced nowhere.
        The 78 retire with their dialogs as those become LCL forms; the 9 are
        dead. Neither is this tool's problem.

THE IDENTIFIERS KEEP THEIR TC_/RC_ SPELLING, deliberately. The name is the
translation key -- in `msgctxt` and in the `#:` reference po_rekey.py added --
and a rename is a new key with no translation behind it. ~417 of these are
finished native-speaker work.

Values are re-encoded through pasconsts.encode_string_expr, so `#13`
concatenation and doubled-quote escapes survive exactly as the compiler sees
them today. Section banners and trailing comments are carried across: they are
the only context a translator gets.

Usage
-----
  python tools/i18n/pas2res.py --out ../tr4w/src/uTR4WStrings.pas
  python tools/i18n/pas2res.py --out - --check     # counts only, writes nothing
"""

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pasconsts

UNIT_NAME = "uTR4WStrings"

# THESE SIXTEEN CANNOT BE resourcestring, AND THE COMPILER SAYS SO.
#
# A resourcestring is a VARIABLE the run time replaces; a typed constant is
# folded at compile time. So a string used to initialise one cannot be a
# resourcestring:
#
#     tContinentArray : array[ContinentType] of PAnsiChar = (TC_C9_UNKNOWN, ...)
#     (mweName: 'FOOT SWITCH'; ... mweText: TC_FOOTSW; ...)
#     ( Text: RC_BAND; Width: 4; ... )
#
# FPC reports "Incompatible types: got AnsiString expected PChar", which is
# accurate and reads like a cast problem rather than a lifetime one.
#
# They are emitted as `const` in the same unit, under the same names, so every
# call site is unchanged and nothing else in the cut-over has to care. The cost
# is that these sixteen are NOT TRANSLATABLE until the three tables that hold
# them are filled at run time instead of being typed constants -- two main-window
# labels, six column headings and the eight continent names.
#
# THE LIST IS SELF-POLICING. Add a seventeenth use in a constant table and the
# build fails on that exact line; it cannot rot silently.
MUST_STAY_CONST = set()   # EMPTY, and that is the point -- see below.
#
# It held sixteen names until 2026-08-27. Each initialised a TYPED CONSTANT
# of PAnsiChar -- the continent array, two main-window element rows, six log
# column headings -- and a typed constant is folded at compile time, where a
# resourcestring is a variable replaced at run time. So those sixteen could
# not move, and the compiler said so rather than shipping English silently.
#
# All four such tables are filled at run time now (VC.InitializeStringTables
# and uNet.InitializeNetworkColumnTitles), so nothing has to stay behind.
#
# TWO WARNINGS FOR WHOEVER ADDS THE NEXT ONE.
#
# The list was an UNDERCOUNT while it stood, because it was written from a
# build that stopped at the first unit with errors. MainUnit's PCharDayTags
# had the same defect and never appeared here. A partial build is a partial
# list; walk the tables, do not trust the last error log.
#
# And PAnsiChar is only the half the compiler catches. A table whose field
# is `string` accepts a resourcestring, folds the English in, and TRANSLATES
# NOTHING -- no error, no warning. uMenu holds 206 such rows. Silence there
# means the fold happened, not that it worked.

HEADER = """unit {unit};

{{
  THE APPLICATION'S USER-FACING TEXT, AS resourcestring.

  GENERATED by tools/i18n/pas2res.py from src/lang/tr4w_consts_eng.pas.
  Do not hand-edit: regenerate. To change the ENGLISH, change it in the .po
  catalogue and run po2pas.py, or change the table and regenerate -- either
  way the change flows from one place.

  WHY resourcestring AND NOT const. The compiler puts these in a resource
  string table and emits {unit}.rsj beside the object file, so rstconv can
  extract them and LazUtils' Translations unit can REPLACE them at run time
  from a .po. One binary, every language. A const is inlined into code and is
  invisible to all of that.

  THE IDENTIFIER IS THE TRANSLATION KEY. It appears in the catalogues twice --
  as msgctxt and as the `#: {unitlower}:<name>` reference the run-time loader
  matches on. RENAMING ONE ORPHANS ITS TRANSLATION IN EVERY LANGUAGE, silently.
  That is why these kept their TC_/RC_ spelling when they moved here, against
  the S<Area><Thing> convention uAppStrings uses for strings written new.

  RC_ constants that appear ONLY in res/Tr4w.rc are deliberately absent: their
  text reaches the screen from the compiled .RES, so a resourcestring here
  would translate nothing. They retire as their dialogs become LCL forms.
}}

interface
"""

FOOTER = """
implementation

end.
"""


def code_referenced_rc(src_root, lang_dir, names):
   """Which RC_ names any Pascal source outside the language tables mentions.

   Case-insensitive: Pascal is, and TR4W spells the same identifier three ways.
   Walks by extension rather than glob -- src/trdos is UPPERCASE .PAS and a
   case-sensitive pattern silently misses 27 files there.
   """
   blob = []
   for dirpath, _dirnames, filenames in os.walk(src_root):
      if os.path.normcase(dirpath).startswith(os.path.normcase(lang_dir)):
         continue
      for fn in filenames:
         if fn.lower().endswith((".pas", ".inc", ".dpr")):
            with open(os.path.join(dirpath, fn), encoding="utf-8", errors="replace") as fh:
               blob.append(fh.read())
   text = "\n".join(blob).lower()
   return {n for n in names if re.search(r"\b" + re.escape(n.lower()) + r"\b", text)}


def build(eng_path, src_root, lang_dir):
   # (decls, lines, form) -- only the declarations are wanted here.
   tc, _lines, _form = pasconsts.parse_lang_file(eng_path, prefix="TC_")
   rc, _lines, _form = pasconsts.parse_lang_file(eng_path, prefix="RC_")
   tc = [d for d in tc if d.name]
   rc = [d for d in rc if d.name]

   keep = code_referenced_rc(src_root, lang_dir, {d.name for d in rc})
   rc_kept = [d for d in rc if d.name in keep]

   # THE FIVE THAT CARRY NEITHER PREFIX, and were silently dropped until
   # 2026-08-27 because this tool only ever asked for TC_ and RC_:
   #
   #   uMenu.pas(581,38) Error: Identifier not found "HELP_WORD"
   #
   # CANCEL_WORD, CLOSE_WORD, EXIT_WORD, HELP_WORD and OK_WORD are as
   # user-facing as anything with a prefix -- they are the button captions --
   # and a naming convention is not a reason to leave them untranslated. Taken
   # by suffix rather than by a hardcoded list, so a sixth is picked up too;
   # RC_EDIT_WORD already comes through the RC_ pass and must not be doubled.
   allsyms, _lines, _form = pasconsts.parse_lang_file(eng_path, prefix="")
   words = [d for d in allsyms
            if d.name and d.name.endswith("_WORD")
            and not d.name.upper().startswith(("TC_", "RC_"))]

   return tc, rc_kept, len(rc) - len(rc_kept), words


def emit(decls_groups):
   out = [HEADER.format(unit=UNIT_NAME, unitlower=UNIT_NAME.lower())]

   # The const block first -- see MUST_STAY_CONST for why these sixteen cannot
   # be resourcestrings. Same unit and same names, so no call site knows.
   fixed = [d for _t, decls in decls_groups for d in decls
            if d.name.upper() in MUST_STAY_CONST]
   if fixed:
      out.append("const\n"
                 "   { NOT TRANSLATABLE YET, and the compiler is what says so.\n"
                 "     Each of these initialises a TYPED CONSTANT -- the continent\n"
                 "     array, two main-window element rows, six column headings --\n"
                 "     and a typed constant is folded at compile time, where a\n"
                 "     resourcestring is a variable replaced at run time.\n"
                 "\n"
                 "     They become translatable when those three tables are filled\n"
                 "     at run time instead. That also retires the PAnsiChar they are\n"
                 "     declared as. }\n")
      width = max(len(d.name) for d in fixed)
      for d in fixed:
         out.append("   %-*s = %s;\n" % (width, d.name,
                                         pasconsts.encode_string_expr(d.value)))
      out.append("\nresourcestring\n")
   else:
      # NOT optional just because the const block above is empty. This used to
      # be emitted only inside that branch, so emptying MUST_STAY_CONST left a
      # unit whose declarations followed `interface` with no section keyword:
      #   uTR4WStrings.pas(34,4) Fatal: Syntax error, "IMPLEMENTATION" expected
      #   but "identifier TC_TRANSLATION_LANGUAGE" found
      out.append("\nresourcestring\n")

   for title, decls in decls_groups:
      decls = [d for d in decls if d.name.upper() not in MUST_STAY_CONST]
      out.append("\n   { %s }\n\n" % title)
      width = max((len(d.name) for d in decls), default=0)
      last_context = None
      for d in decls:
         if d.context and d.context != last_context:
            out.append("\n   // %s\n" % d.context)
            last_context = d.context
         value = pasconsts.encode_string_expr(d.value)
         line = "   %-*s = %s;" % (width, d.name, value)
         if d.comment:
            line += "   //%s" % d.comment
         out.append(line + "\n")
   out.append(FOOTER)
   return "".join(out)


def main():
   ap = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
   ap.add_argument("--out", required=True, help="target .pas, or - for none")
   ap.add_argument("--check", action="store_true", help="counts only, write nothing")
   ap.add_argument("--repo", default=None, help="repo root holding tr4w/src")
   args = ap.parse_args()

   here = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
   repo = args.repo or here
   src_root = os.path.join(repo, "tr4w", "src")
   lang_dir = os.path.join(src_root, "lang")
   eng = os.path.join(lang_dir, "tr4w_consts_eng.pas")
   if not os.path.exists(eng):
      print("no English table at " + eng)
      return 2

   tc, rc, dropped, words = build(eng, src_root, lang_dir)
   print("  TC_ emitted            : %4d" % len(tc))
   print("  RC_ emitted (code-used): %4d" % len(rc))
   print("  RC_ left behind (.rc)  : %4d" % dropped)
   print("  unprefixed *_WORD      : %4d" % len(words))
   print("  total resourcestrings  : %4d" % (len(tc) + len(rc) + len(words)))

   text = emit([("TC_ -- messages, prompts and labels", tc),
                ("RC_ -- reachable from Pascal code", rc),
                ("Unprefixed -- the shared button captions", words)])

   nonascii = sorted({c for c in text if ord(c) > 127})
   if nonascii:
      print("  NOTE non-ASCII in English: " + " ".join(repr(c) for c in nonascii[:10]))

   if args.check or args.out == "-":
      print("\nCheck only -- nothing written.")
      return 0

   # CRLF, and no BOM: this unit is pure ASCII English. The BOM rule applies to
   # the per-language tables, whose non-ASCII would otherwise be decoded with
   # the build machine's ANSI codepage.
   with open(args.out, "w", encoding="utf-8", newline="\r\n") as fh:
      fh.write(text)
   print("\nwrote %s (%d lines)" % (args.out, text.count("\n") + 1))
   return 0


if __name__ == "__main__":
   sys.exit(main())
