"""Generate the resourcestring unit from the English constant tables.

`tr4w/src/lang/tr4w_consts_eng.pas` is a `{$INCLUDE}` fragment of `const`
declarations, one per language, selected by a LANG_xxx define at compile time.
The replacement is ONE binary with `resourcestring`, translated at run time from
a .po (NY4I, 2026-08-13). This writes that unit.

WHAT IT EMITS, AND WHAT IT LEAVES BEHIND
----------------------------------------
  TC_*  all of them -- these are consumed from Pascal.

  RC_*  ONLY those a Pascal source actually references. The rest are captions
        inside `res/Tr4w.rc`, whose text reaches the screen through the compiled
        .RES, not through this constant -- so declaring a resourcestring for one
        would translate nothing. Measured 2026-08-26 across 250 RC_:
            10 code only, 153 both, 78 .rc only, 9 referenced nowhere.
        The 78 retire with their dialogs as those become LCL forms; the 9 are
        dead. Neither is this tool's problem.

THE IDENTIFIERS KEEP THEIR TC_/RC_ SPELLING, deliberately. The name is the
translation key -- in `msgctxt` and in the `#:` reference po_rekey.py added --
and a rename is a new key with no translation behind it. ~417 of these are
finished native-speaker work.

Values are re-encoded through pasconsts.encode_string_expr, so `#13`
concatenation and doubled-quote escapes survive exactly as the compiler sees
them today. Section banners and trailing comments are carried across: they are
the only context a translator gets.

Usage
-----
  python tools/i18n/pas2res.py --out ../tr4w/src/uTR4WStrings.pas
  python tools/i18n/pas2res.py --out - --check     # counts only, writes nothing
"""

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pasconsts

UNIT_NAME = "uTR4WStrings"

HEADER = """unit {unit};

{{
  THE APPLICATION'S USER-FACING TEXT, AS resourcestring.

  GENERATED by tools/i18n/pas2res.py from src/lang/tr4w_consts_eng.pas.
  Do not hand-edit: regenerate. To change the ENGLISH, change it in the .po
  catalogue and run po2pas.py, or change the table and regenerate -- either
  way the change flows from one place.

  WHY resourcestring AND NOT const. The compiler puts these in a resource
  string table and emits {unit}.rsj beside the object file, so rstconv can
  extract them and LazUtils' Translations unit can REPLACE them at run time
  from a .po. One binary, every language. A const is inlined into code and is
  invisible to all of that.

  THE IDENTIFIER IS THE TRANSLATION KEY. It appears in the catalogues twice --
  as msgctxt and as the `#: {unitlower}:<name>` reference the run-time loader
  matches on. RENAMING ONE ORPHANS ITS TRANSLATION IN EVERY LANGUAGE, silently.
  That is why these kept their TC_/RC_ spelling when they moved here, against
  the S<Area><Thing> convention uAppStrings uses for strings written new.

  RC_ constants that appear ONLY in res/Tr4w.rc are deliberately absent: their
  text reaches the screen from the compiled .RES, so a resourcestring here
  would translate nothing. They retire as their dialogs become LCL forms.
}}

interface

resourcestring
"""

FOOTER = """
implementation

end.
"""


def code_referenced_rc(src_root, lang_dir, names):
   """Which RC_ names any Pascal source outside the language tables mentions.

   Case-insensitive: Pascal is, and TR4W spells the same identifier three ways.
   Walks by extension rather than glob -- src/trdos is UPPERCASE .PAS and a
   case-sensitive pattern silently misses 27 files there.
   """
   blob = []
   for dirpath, _dirnames, filenames in os.walk(src_root):
      if os.path.normcase(dirpath).startswith(os.path.normcase(lang_dir)):
         continue
      for fn in filenames:
         if fn.lower().endswith((".pas", ".inc", ".dpr")):
            with open(os.path.join(dirpath, fn), encoding="utf-8", errors="replace") as fh:
               blob.append(fh.read())
   text = "\n".join(blob).lower()
   return {n for n in names if re.search(r"\b" + re.escape(n.lower()) + r"\b", text)}


def build(eng_path, src_root, lang_dir):
   # (decls, lines, form) -- only the declarations are wanted here.
   tc, _lines, _form = pasconsts.parse_lang_file(eng_path, prefix="TC_")
   rc, _lines, _form = pasconsts.parse_lang_file(eng_path, prefix="RC_")
   tc = [d for d in tc if d.name]
   rc = [d for d in rc if d.name]

   keep = code_referenced_rc(src_root, lang_dir, {d.name for d in rc})
   rc_kept = [d for d in rc if d.name in keep]

   return tc, rc_kept, len(rc) - len(rc_kept)


def emit(decls_groups):
   out = [HEADER.format(unit=UNIT_NAME, unitlower=UNIT_NAME.lower())]
   for title, decls in decls_groups:
      out.append("\n   { %s }\n\n" % title)
      width = max((len(d.name) for d in decls), default=0)
      last_context = None
      for d in decls:
         if d.context and d.context != last_context:
            out.append("\n   // %s\n" % d.context)
            last_context = d.context
         value = pasconsts.encode_string_expr(d.value)
         line = "   %-*s = %s;" % (width, d.name, value)
         if d.comment:
            line += "   //%s" % d.comment
         out.append(line + "\n")
   out.append(FOOTER)
   return "".join(out)


def main():
   ap = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
   ap.add_argument("--out", required=True, help="target .pas, or - for none")
   ap.add_argument("--check", action="store_true", help="counts only, write nothing")
   ap.add_argument("--repo", default=None, help="repo root holding tr4w/src")
   args = ap.parse_args()

   here = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
   repo = args.repo or here
   src_root = os.path.join(repo, "tr4w", "src")
   lang_dir = os.path.join(src_root, "lang")
   eng = os.path.join(lang_dir, "tr4w_consts_eng.pas")
   if not os.path.exists(eng):
      print("no English table at " + eng)
      return 2

   tc, rc, dropped = build(eng, src_root, lang_dir)
   print("  TC_ emitted            : %4d" % len(tc))
   print("  RC_ emitted (code-used): %4d" % len(rc))
   print("  RC_ left behind (.rc)  : %4d" % dropped)
   print("  total resourcestrings  : %4d" % (len(tc) + len(rc)))

   text = emit([("TC_ -- messages, prompts and labels", tc),
                ("RC_ -- reachable from Pascal code", rc)])

   nonascii = sorted({c for c in text if ord(c) > 127})
   if nonascii:
      print("  NOTE non-ASCII in English: " + " ".join(repr(c) for c in nonascii[:10]))

   if args.check or args.out == "-":
      print("\nCheck only -- nothing written.")
      return 0

   # CRLF, and no BOM: this unit is pure ASCII English. The BOM rule applies to
   # the per-language tables, whose non-ASCII would otherwise be decoded with
   # the build machine's ANSI codepage.
   with open(args.out, "w", encoding="utf-8", newline="\r\n") as fh:
      fh.write(text)
   print("\nwrote %s (%d lines)" % (args.out, text.count("\n") + 1))
   return 0


if __name__ == "__main__":
   sys.exit(main())
