unit uMainGrids;

(* THE TWO GRIDS ON THE MAIN WINDOW THAT ARE NOT TMainWindowElement.

  The score totals table -- eight columns by four rows, under seven band
  headers -- and the QSO-need / mult-need band strips at top right. Sixty-seven
  windows between them, and until now the last children of the main form that
  were not LCL controls: CreateTotalWindows, CreateQSONeedWindows and
  CreateMultsWindows built raw Win32 STATICs and published their HWNDs in eight
  global arrays for uTotal and LOGEDIT to operate on.

  WHAT CHANGES HERE IS NOT THE WIDGET, IT IS WHO KNOWS WHAT.

  No caller gets a control. They get SetTotalsCell, HighlightTotalsColumn and
  SetMultNeedVisible -- what they MEAN, not a window to poke. LOGEDIT called
  Windows.ShowWindow nine times with a handle out of a global array; it now
  names a band and a mode, and this unit is the only thing that knows "mult
  needed on 20m in CW" is a panel in row one.

  That is worth more than the LCL move. A window handle in a global array is
  addressable by anything holding the array, and this tree has already paid
  for that: one out-of-range write to TotWinHandles[7,4] landed in
  TotWinheadHandles[1] -- a LIVE WINDOW HANDLE in the next variable -- and
  failed later, elsewhere, intermittently. uTotal.pas carries the full account.
  The two arrays cannot be adjacent any more because neither exists.

  THE PANELS ARE DESIGNED, in uMainForm.lfm, generated by
  tools/gen_main_elements.py from the same formulas the deleted creators used.
  Designed rather than built here so that opening tr4w.lpi and pressing F12
  shows them named and selectable alongside the rest of the main window
  (NY4I, 2026-09-04).

  As with those elements, THE .lfm BOUNDS AND CAPTIONS ARE A DESIGN-TIME
  PICTURE. The band captions are assigned at bind time from BandStringsArray,
  which is the one place band names are spelled. *)

{$MODE Delphi}
{$MODESWITCH UnicodeStrings}

interface

uses
   Classes, Controls, VC;   { Controls: TCaption }

const
   (* THE TOTALS GRID'S SHAPE, AND THE SINGLE SOURCE OF TRUTH FOR IT. These
     bounds were the two array declarations in VC.pas; every loop over the grid
     took its limits from High() rather than a literal, and does the same with
     these.

     FOUR ROWS IS ONE SHORT FOR SOME CONTESTS, and that is a known original TR4W
     defect rather than a port regression -- D7 has the identical four-row
     arrays and no bounds check at all.

     The totals window shows one row per category, and a contest can want more
     than four: up to three QSO rows (CW, SSB, DIG) plus Domestic, DX, Prefix
     and Zone multipliers. Winter Field Day WITH DIGITAL QSOs needs five. The
     fifth write went one past the end and, at column 7, landed in the next
     variable -- which was another live window-handle array.

     WIDENING TO SIX OR SEVEN ROWS WORKS -- DX Mults appears and the numbers are
     right -- but the extra rows overrun the log area below, because these are
     absolutely positioned and nothing reflows. That is what the main window's
     move to Align and anchors is for; until it lands, the grid stays at four
     and SetTotalsCell guards the overflow, dropping and LOGGING the extra
     category rather than corrupting anything.

     (The note this replaces said the fix belonged with a move to FMX. FMX was
     abandoned in August; the LCL conversion is what actually arrived.) *)
   TOTALS_COLUMNS      = 8;
   TOTALS_ROWS         = 4;
   TOTALS_FIRST_HEADER = 1;

(* Find the designed panels. Call once, after the main form exists and before
  anything writes to a grid. A name that is not in the .lfm is REPORTED --
  silence would mean a column that simply never updates. *)
procedure BindMainGrids;

(* LAY THE GRIDS OUT AT THE LIVE FONT SCALE.

  The .lfm holds the design-time picture, computed at the default ws of 17.
  `ws` follows the operator's WindowSize setting, so every other element on the
  main window is positioned in code from TWindows[] * ws -- and these must be
  too, or the grids stay at the default scale while the rest of the window
  moves. Call after the main window's ws is known, once per layout. *)
procedure PositionMainGrids;

(* Caption and reveal the need-strip row labels for the contest at hand.
  Replaces the conditional CREATION the two deleted routines did: the row-two
  labels exist either way now, and this decides whether they are seen. *)
procedure ConfigureNeedRows(const aQSOByMode, aMultByMode: boolean);

procedure SetTotalsCell(const aColumn, aRow: integer; const aText: string);
procedure SetTotalsHeader(const aColumn: integer; const aText: TCaption);

(* Colour the band header of the column in play, and restore the rest. The
  Win32 form of this was a WM_CTLCOLORSTATIC handler keyed on control id plus
  an InvalidateRect loop; the loop ran 1..6 and never repainted header 7, so
  the All column's highlight could go stale. Setting the property instead has
  no such gap. *)
procedure HighlightTotalsColumn(const aColumn: integer);

procedure SetQSONeedVisible(const aMode: ModeType; const aBand: BandType;
                            const aVisible: boolean);
procedure SetMultNeedVisible(const aMode: ModeType; const aBand: BandType;
                             const aVisible: boolean);

(* SHOW EXACTLY THE BANDS IN aBandMask, in one call.

  aBandMask is the value CreateModeSpecificQSOInfo and
  CreateModeSpecificMultiplierInfo produce: bit Ord(Band) set means that band
  is still needed. Taking it whole rather than a band at a time is what lets
  LOGEDIT say what it means in one line -- it had SIX copies of the same
  band loop and bit test, one per mode per strip, each with its own
  ShowWindow call and its own integer() cast of a boolean. *)
procedure SetQSONeedBands(const aMode: ModeType; const aBandMask: Cardinal);
procedure SetMultNeedBands(const aMode: ModeType; const aBandMask: Cardinal);

implementation

uses
   SysUtils, Graphics, Log4D, uElementPanel, uMainForm, MainUnit;

type
   (* Row one is CW when the contest counts by mode and Both when it does not;
     row two is SSB and is shown only in the by-mode case. *)
   TNeedRow = 1..2;

   (* ONE TYPE FOR BOTH STRIPS, so the routine that walks a strip can be
     written once and take either. They are the same shape because they are
     the same thing twice: a row per mode, a cell per band. *)
   TNeedGrid = array[TNeedRow, Band160..Band10] of TElementPanel;

var
   GTotalsCell: array[0..TOTALS_COLUMNS - 1, 0..TOTALS_ROWS - 1] of TElementPanel;
   GTotalsHead: array[TOTALS_FIRST_HEADER..TOTALS_COLUMNS - 1] of TElementPanel;

   GQSONeed:      TNeedGrid;
   GQSONeedLabel: array[TNeedRow] of TElementPanel;
   GMultNeed:     TNeedGrid;
   GMultNeedLabel: array[TNeedRow] of TElementPanel;

   GBound: boolean = False;

   logger: TLogLogger;

function BindPanel(const aName: string): TElementPanel;
var
   c: TComponent;
begin
   Result := nil;

   if TR4WMainForm = nil then
      begin
      Exit;
      end;

   c := TR4WMainForm.FindComponent(AnsiString(aName));

   if c is TElementPanel then
      begin
      Result := TElementPanel(c);
      end
   else
      begin
      if logger <> nil then
         begin
         logger.Error('[MainGrids] uMainForm.lfm has no TElementPanel named %s -- ' +
                      'run tools/gen_main_elements.py', [aName]);
         end;
      end;
end;

(* The colours a panel takes from the element whose role it shares. The mult
  strip reads mweNewMultStatus, which is what the old MULTSARRAYWINDOW branch
  of DrawWindows looked up; everything else reads mweWholeScreen, the default
  that branch fell through to. *)
procedure ApplyElementColors(const aPanel: TElementPanel;
                            const aElement: TMainWindowElement);
begin
   if aPanel = nil then
      begin
      Exit;
      end;

   aPanel.Color := tr4wColorsArray[TWindows[aElement].mweBackG];
   aPanel.Font.Color := tr4wColorsArray[TWindows[aElement].mweColor];
end;

procedure PrepareNeedPanel(const aPanel: TElementPanel;
                          const aElement: TMainWindowElement;
                          const aCaption: TCaption);
begin
   if aPanel = nil then
      begin
      Exit;
      end;

   ApplyMainFontTo(aPanel.Font);
   aPanel.BaseFontHeight := -aPanel.Font.Height;
   ApplyElementColors(aPanel, aElement);
   aPanel.Caption := aCaption;
end;

procedure BindMainGrids;
var
   c, r: integer;
   row: TNeedRow;
   band: BandType;
   suffix: string;
begin
   (* NO FORM, NOTHING TO BIND, AND SAY IT ONCE. Without this, every one of the
     110 lookups reports its own missing panel -- which is not a diagnosis, it
     is a wall. The headless /EXPORT path is the case that matters: it runs
     through this on its way to writing the files. *)
   if TR4WMainForm = nil then
      begin
      if logger <> nil then
         begin
         logger.Debug('[MainGrids] no main form -- grids not bound ' +
                      '(headless export, or called too early)');
         end;
      Exit;
      end;

   for c := 0 to TOTALS_COLUMNS - 1 do
      begin
      for r := 0 to TOTALS_ROWS - 1 do
         begin
         GTotalsCell[c, r] := BindPanel(Format('pnlTotalCell_%d_%d', [c, r]));
         PrepareNeedPanel(GTotalsCell[c, r], mweWholeScreen, '');
         end;
      end;

   for c := TOTALS_FIRST_HEADER to TOTALS_COLUMNS - 1 do
      begin
      GTotalsHead[c] := BindPanel(Format('pnlTotalHead_%d', [c]));
      PrepareNeedPanel(GTotalsHead[c], mweWholeScreen, '');
      end;

   for row := Low(TNeedRow) to High(TNeedRow) do
      begin
      GQSONeedLabel[row] := BindPanel(Format('pnlQSONeedR%dLabel', [row]));
      GMultNeedLabel[row] := BindPanel(Format('pnlMultNeedR%dLabel', [row]));

      for band := Band160 to Band10 do
         begin
         (* ONE SPELLING OF THE BAND NAMES. The generator builds the component
           names from the same six strings, so a band renamed in VC.pas renames
           the panel and this lookup together. *)
         suffix := BandStringsArrayWithOutSpaces[band];

         GQSONeed[row, band] := BindPanel(Format('pnlQSONeedR%d_%s', [row, suffix]));
         PrepareNeedPanel(GQSONeed[row, band], mweWholeScreen,
                          BandStringsArray[band]);

         GMultNeed[row, band] := BindPanel(Format('pnlMultNeedR%d_%s', [row, suffix]));
         PrepareNeedPanel(GMultNeed[row, band], mweNewMultStatus,
                          BandStringsArray[band]);
         end;
      end;

   GBound := True;
end;

(* THE COLUMN GEOMETRY, AND THE ONE PLACE THAT KNOWS IT.

  CreateTotalWindow spelled this as `const w = 2.5` and round(ws * w) in four
  separate expressions. Column 0 is the label column, column 7 ("All") is three
  units wide, and the band columns between them are one pitch each.

  THE BAND COLUMNS USED TO START ONE PIXEL INSIDE THE LABEL COLUMN. Column 0 is
  ws * 5 wide -- 85 at the default scale, which is deliberate: it has to line up
  with the clock panels stacked directly above it, and TWindows[] gives those a
  width of 5 units. But the band columns were placed at (column + 1) * pitch,
  and pitch is round(ws * 2.5) = 42, so column 1 began at 84. Every row of the
  grid, and the header above it, overlapped the label column's sunken border by
  a pixel, at every font size.

  Nobody was ever going to see it. Lint-FormOverlap did, the moment these
  became designed controls whose geometry something could read -- eight pairs,
  then two more against the clock panels. The band columns start AFTER the
  label column now.

  gen_main_elements.py computes the same thing for the design-time picture.
  Two languages, so two copies; keep them in step. *)
function TotalsColumnPitch(const aWS: integer): integer;
begin
   Result := Round(aWS * 2.5);
end;

function TotalsLabelWidth(const aWS: integer): integer;
begin
   Result := aWS * 5;
end;

procedure TotalsColumnGeometry(const aWS, aColumn: integer;
                              out aLeft, aWidth: integer);
begin
   if aColumn = 0 then
      begin
      aLeft := 0;
      aWidth := TotalsLabelWidth(aWS);
      end
   else
      begin
      aLeft := TotalsLabelWidth(aWS) + (aColumn - 1) * TotalsColumnPitch(aWS);
      if aColumn = TOTALS_COLUMNS - 1 then
         begin
         aWidth := aWS * 3;
         end
      else
         begin
         aWidth := TotalsColumnPitch(aWS);
         end;
      end;
end;

procedure PositionMainGrids;
var
   c, r, left, width, needLeft, cellWidth: integer;
   row: TNeedRow;
   band: BandType;

   procedure Place(const aPanel: TElementPanel;
                   const aLeft, aTop, aWidth, aHeight: integer);
   begin
      if aPanel <> nil then
         begin
         aPanel.SetBounds(aLeft, aTop, aWidth, aHeight);
         end;
   end;

begin
   if not GBound then
      begin
      Exit;
      end;

   for c := 0 to TOTALS_COLUMNS - 1 do
      begin
      TotalsColumnGeometry(ws, c, left, width);

      for r := 0 to TOTALS_ROWS - 1 do
         begin
         Place(GTotalsCell[c, r], left, ws * 2 + r * ws, width, ws);
         end;

      if c >= TOTALS_FIRST_HEADER then
         begin
         (* The header row is TWO cells tall and sits above the grid. *)
         Place(GTotalsHead[c], left, 0, width, ws * 2);
         end;
      end;

   (* The need strips hang off the RIGHT of the window, so their origin moves
     with the window width rather than being a fixed column. *)
   needLeft := MainWindowChildsWidth - RightTopWidth;
   cellWidth := ws * 2;

   for row := Low(TNeedRow) to High(TNeedRow) do
      begin
      Place(GQSONeedLabel[row], needLeft, ws * row, cellWidth, ws);
      Place(GMultNeedLabel[row], needLeft, ws * (row + 3), cellWidth, ws);

      for band := Band160 to Band10 do
         begin
         left := needLeft + (Ord(band) - Ord(Band160) + 1) * cellWidth;

         (* Two pixels narrower than the pitch, which is what separates one
           band's cell from the next -- the strips have no borders. *)
         Place(GQSONeed[row, band], left, ws * row, cellWidth - 2, ws);
         Place(GMultNeed[row, band], left, ws * (row + 3), cellWidth - 2, ws);
         end;
      end;
end;

procedure ConfigureNeedRows(const aQSOByMode, aMultByMode: boolean);

   procedure LabelRows(const aLabels: array of TElementPanel;
                       const aByMode: boolean;
                       const aElement: TMainWindowElement);
   begin
      (* Open-array indexing is zero-based; the rows are one-based. *)
      PrepareNeedPanel(aLabels[0], aElement, '');
      PrepareNeedPanel(aLabels[1], aElement, '');

      if aByMode then
         begin
         aLabels[0].Caption := 'CW:';
         aLabels[1].Caption := 'SSB:';
         end
      else
         begin
         aLabels[0].Caption := 'Both:';
         end;

      aLabels[0].Visible := True;
      aLabels[1].Visible := aByMode;
   end;

begin
   if not GBound then
      begin
      Exit;
      end;

   if (GQSONeedLabel[1] = nil) or (GQSONeedLabel[2] = nil) or
      (GMultNeedLabel[1] = nil) or (GMultNeedLabel[2] = nil) then
      begin
      Exit;
      end;

   (* THE QSO STRIP'S ROW-ONE LABEL WAS BLANK WHEN NOT BY MODE, where the mult
     strip's said 'Both:'. Kept: that is what the two creators did, and the QSO
     strip sits under a heading that already says what it is. *)
   LabelRows([GQSONeedLabel[1], GQSONeedLabel[2]], aQSOByMode, mweWholeScreen);
   if not aQSOByMode then
      begin
      GQSONeedLabel[1].Caption := '';
      end;

   LabelRows([GMultNeedLabel[1], GMultNeedLabel[2]], aMultByMode, mweNewMultStatus);
end;

procedure SetTotalsCell(const aColumn, aRow: integer; const aText: string);
begin
   (* THE GUARD, MOVED HERE FROM uTotal.TotalTextOut so there is one of it.

     Row is a running counter incremented per category, and enough conditional
     rows -- CW plus Phone plus Digital, or the mult labels -- reach Row = 4 in
     a four-row grid. NY4I hit exactly that at startup 2026-08-07:

        uTotal.TotalTextOut ('DX Mults', 0, 4)     <- one past the end

     WITH RANGE CHECKING OFF, which is this project's setting, that did not
     raise. It wrote into whatever followed, and for Column 7 what followed the
     handle array was ANOTHER handle array -- so a live window handle was
     silently corrupted and something unrelated failed later. That specific
     mechanism is gone with the arrays, but the caller is still counting past
     the end of the grid and still needs telling. *)
   if (aColumn < 0) or (aColumn > TOTALS_COLUMNS - 1) or
      (aRow < 0) or (aRow > TOTALS_ROWS - 1) then
      begin
      (* REPORTED, not swallowed: a dropped label means the totals window shows
        fewer categories than the contest has, and an operator has no way to
        discover that beyond noticing a blank line. *)
      if logger <> nil then
         begin
         logger.Warn('[MainGrids] totals cell (%d,%d) is outside the %dx%d grid; ' +
                     'text "%s" not shown',
                     [aColumn, aRow, TOTALS_COLUMNS, TOTALS_ROWS, aText]);
         end;
      Exit;
      end;

   if GTotalsCell[aColumn, aRow] = nil then
      begin
      Exit;
      end;

   (* Compared before assigning, which is what the parallel TotWinHandlesFilled
     array used to buy. One less thing to keep in step. *)
   if GTotalsCell[aColumn, aRow].Caption <> aText then
      begin
      GTotalsCell[aColumn, aRow].Caption := aText;
      end;
end;

procedure SetTotalsHeader(const aColumn: integer; const aText: TCaption);
begin
   if (aColumn < TOTALS_FIRST_HEADER) or (aColumn > TOTALS_COLUMNS - 1) or
      (GTotalsHead[aColumn] = nil) then
      begin
      Exit;
      end;

   if GTotalsHead[aColumn].Caption <> aText then
      begin
      GTotalsHead[aColumn].Caption := aText;
      end;
end;

procedure HighlightTotalsColumn(const aColumn: integer);
var
   c: integer;
begin
   for c := TOTALS_FIRST_HEADER to TOTALS_COLUMNS - 1 do
      begin
      if GTotalsHead[c] = nil then
         begin
         Continue;
         end;

      if c = aColumn then
         begin
         GTotalsHead[c].Color := tr4wColorsArray[trBlue];
         GTotalsHead[c].Font.Color := tr4wColorsArray[trWhite];
         end
      else
         begin
         ApplyElementColors(GTotalsHead[c], mweWholeScreen);
         end;
      end;
end;

function NeedRowForMode(const aMode: ModeType): TNeedRow;
begin
   (* Phone is row two. CW and Both are both row one -- which is why a caller
     can pass the same mode it passed to CreateModeSpecificMultiplierInfo and
     need not know the strip has rows at all. *)
   if aMode = Phone then
      begin
      Result := 2;
      end
   else
      begin
      Result := 1;
      end;
end;

procedure SetNeedVisible(const aGrid: TNeedGrid; const aMode: ModeType;
                        const aBand: BandType; const aVisible: boolean);
var
   p: TElementPanel;
begin
   (* THE STRIPS COVER Band160..Band10 ONLY. BandType runs well past 10m -- 6m
     up to Light -- and a caller looping the whole enum would index off the
     end of a six-band array with range checking off, which is the same class
     of fault the totals guard exists for. *)
   if (aBand < Band160) or (aBand > Band10) then
      begin
      Exit;
      end;

   p := aGrid[NeedRowForMode(aMode), aBand];
   if p <> nil then
      begin
      p.Visible := aVisible;
      end;
end;

procedure SetNeedBands(const aGrid: TNeedGrid; const aMode: ModeType;
                      const aBandMask: Cardinal);
var
   band: BandType;
begin
   for band := Band160 to Band10 do
      begin
      SetNeedVisible(aGrid, aMode, band,
                     (aBandMask and (1 shl Ord(band))) <> 0);
      end;
end;

procedure SetQSONeedVisible(const aMode: ModeType; const aBand: BandType;
                            const aVisible: boolean);
begin
   SetNeedVisible(GQSONeed, aMode, aBand, aVisible);
end;

procedure SetMultNeedVisible(const aMode: ModeType; const aBand: BandType;
                             const aVisible: boolean);
begin
   SetNeedVisible(GMultNeed, aMode, aBand, aVisible);
end;

procedure SetQSONeedBands(const aMode: ModeType; const aBandMask: Cardinal);
begin
   SetNeedBands(GQSONeed, aMode, aBandMask);
end;

procedure SetMultNeedBands(const aMode: ModeType; const aBandMask: Cardinal);
begin
   SetNeedBands(GMultNeed, aMode, aBandMask);
end;

initialization
   logger := TLogLogger.GetLogger('TR4WDebugLog');

end.
