"""Generate callsigns that exercise EVERY branch of ctyGetZone.

The zone rules are a two-level table -- district digit, then first suffix
letter -- and several branches (UA0 has nine letter groups, UA9 has five)
cannot be reached by any callsign in the corpus. A characterisation net that
does not reach them would let a transcription error through silently, which is
precisely the risk when that table is retyped.

Both zone modes are captured for every call, so one callsign covers its ITU
branch and its CQ branch at once.
"""
import io

LETTERS = [chr(c) for c in range(ord('A'), ord('Z') + 1)]
DIGITS = [str(d) for d in range(10)]

out = []


def note(s):
   out.append('# ' + s)


def every_digit(prefix, tail='AA'):
   for d in DIGITS:
      out.append('%s%s%s' % (prefix, d, tail))


def every_letter(prefix, digit, tail='A'):
   for L in LETTERS:
      out.append('%s%s%s%s' % (prefix, digit, L, tail))


note('=====================================================================')
note('ZONE RULE COVERAGE -- generated by genzone.py, do not hand-edit this')
note('block. Every district digit and every first-suffix-letter branch of')
note('ctyGetZone, for BOTH zone modes.')
note('=====================================================================')

note('--- K: ITU 5,0->7  6,7->6  else 8   |  CQ 1-4->5  5,8,9,0->4  6,7->3')
every_digit('K')
note('--- VE: ITU 1,9->9 2,3->4 4,5->3 6,7->2 | CQ 1,2,9,0->5 3-6->4 7->3 8->2')
every_digit('VE')
note('--- VK: ITU 4,8->55 6->58 else 59   |  CQ 6,8->29 else 30')
every_digit('VK')
note('--- CE: ITU 1-5->14  6,7,8->16  (no else arm)')
every_digit('CE')
note('--- CP: ITU 1,8,9->12  else 14')
every_digit('CP')
note('--- PY: ITU 6,7,8->13  else 15')
every_digit('PY')

note('--- BY: ITU 8,9->43 0->42 else 44  |  CQ 1,2->24 3(letters) 4-8->24')
note('        9(letters) 0->23')
every_digit('BY')
note('--- BY3: CQ G,H,I,J,K,L->23 else 24')
every_letter('BY', '3')
note('--- BY9: CQ M,N,P,Q,R,S->24 else 23')
every_letter('BY', '9')

note('--- LU: ITU first suffix letter V,W,X->16 else 14')
every_letter('LU', '1')
note('--- UN: ITU first suffix letter J,D,V,G->31 else 30')
every_letter('UN', '7')

note('--- UA / UA9: the two-level table. Every digit, and every letter for')
note('    each digit that has a letter sub-map (1, 4, 8, 9, 0).')
every_digit('UA')
for d in ('1', '3', '4', '6', '8', '9', '0'):
   every_letter('UA', d)

io.open('zone-coverage.txt', 'w', encoding='utf-8', newline='\r\n').write(
   '\r\n'.join(out) + '\r\n')
print('generated %d lines (%d callsigns)' %
      (len(out), len([x for x in out if not x.startswith('#')])))
